Repository terrapower/armi, pull requests merged in 2020-08, with the labels that each got.

#123 Define and implement plugin hook to handle MPI resets
  armi/bookkeeping/__init__.py
  armi/operators/operatorMPI.py
  armi/plugins.py
Labels: bug, enhancement

#128 Remove old block homogenized ndens params
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_xtviewdb.py
  armi/physics/fuelPerformance/utils.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
Labels: cleanup

#131 Add grid editor GUI
  .coveragerc
  armi/cli/__init__.py
  armi/cli/gridGui.py
  armi/utils/gridEditor.py
  setup.py
  tox.ini
Labels: enhancement

#130 Move some design-specific methods off of block
  armi/cases/inputModifiers/__init__.py
  armi/cases/inputModifiers/inputModifiers.py
  armi/cases/inputModifiers/neutronicsModifiers.py
  armi/cases/inputModifiers/pinTypeInputModifiers.py
  armi/cases/inputModifiers/tests/__init__.py
  armi/cases/inputModifiers/tests/test_inputModifiers.py
  armi/cases/inputModifiers/tests/test_pinTypeInputModifiers.py
  armi/cases/suiteBuilder.py
  armi/cases/tests/test_suiteBuilder.py
  armi/reactor/blocks.py
  armi/reactor/converters/__init__.py
  armi/reactor/converters/pinTypeBlockConverters.py
  armi/reactor/converters/tests/test_pinTypeBlockConverters.py
  armi/reactor/tests/test_blocks.py
Labels: architecture, cleanup

#137 Fix Be material and add test.
  armi/materials/be9.py
  armi/materials/material.py
  armi/materials/tests/test_be9.py
Labels: bug

#138 Move many block methods to ArmiObject (temporarily).
  armi/physics/neutronics/isotopicDepletion/crossSectionTable.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/physics/neutronics/tests/test_crossSectionTable.py
  armi/reactor/batch.py
  armi/reactor/batchParameters.py
  armi/reactor/blocks.py
  armi/reactor/components/__init__.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/tests/test_composites.py
Labels: architecture, cleanup

#139 Consolidate getDominantMaterial methods into one
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/composites.py
  armi/reactor/converters/meshConverters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_blocks.py
Labels: cleanup

#141 Move energy group code from utils to neutronics
  armi/physics/constants.py
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/const.py
  armi/physics/neutronics/energyGroups.py
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_energyGroups.py
  armi/settings/settingsRules.py
  armi/utils/tests/test_utils.py
  armi/utils/units.py
  doc/gallery-src/framework/run_isotxs.py
Labels: cleanup
