Repository terrapower/armi, pull requests merged in 2020-11, with the labels that each got.

#201 Add support for converting old database flags
  armi/__init__.py
  armi/bookkeeping/db/database3.py
  armi/reactor/composites.py
  armi/reactor/tests/test_composites.py
  armi/utils/__init__.py
  doc/release/0.1.rst
Labels: enhancement

#204 Fix catch-all try/except in __main__
  armi/__main__.py
  armi/cli/__init__.py
  armi/tests/test_apps.py
Labels: bug

#210 Disable gallery line numbers to get rid of space
  doc/conf.py
Labels: documentation

#213 Add permissive option to armi.configure()
  armi/__init__.py
  doc/gallery-src/analysis/run_blockMcnpMaterialCard.py
  doc/gallery-src/analysis/run_hexBlockToRZConversion.py
  doc/gallery-src/analysis/run_hexReactorToRZ.py
  doc/gallery-src/framework/run_blockVolumeFractions.py
  doc/gallery-src/framework/run_chartOfNuclides.py
  doc/gallery-src/framework/run_computeReactionRates.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/gallery-src/framework/run_grids1_hex.py
  doc/gallery-src/framework/run_grids2_cartesian.py
  doc/gallery-src/framework/run_grids3_rzt.py
  doc/gallery-src/framework/run_isotxs.py
  doc/gallery-src/framework/run_isotxs2_matrix.py
  doc/gallery-src/framework/run_materials.py
  doc/gallery-src/framework/run_reactorFacemap.py
  setup.py
Labels: enhancement

#220 Mty/usage app name
  armi/apps.py
  armi/cli/__init__.py
  armi/cli/entryPoint.py
Labels: cleanup
