Repository terrapower/armi, pull requests merged in 2021-12, with the labels that each got.

#497 Adding rules about third-party licensing
  CONTRIBUTING.md
  README.rst
  doc/developer/tooling.rst
Labels: documentation

#495 Validate YAML Files
  armi/settings/settingsIO.py
  armi/tests/test_fuelHandlers.py
  armi/tests/test_lwrInputs.py
  armi/tests/tutorials/c5g7-settings.yaml
Labels: enhancement

#500 Fixed bug where SettingsModifier was using old settings API
  armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py
  armi/reactor/converters/parameterSweeps/tests/test_paramSweepConverters.py
Labels: bug

#505 Add new top-level components input for blueprints.
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/tests/test_blueprints.py
  doc/user/inputs/blueprints.rst
Labels: enhancement

#512 Some cleanup
  .gitignore
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/visualization/tests/test_vis.py
  armi/cli/tests/test_runEntryPoint.py
  armi/reactor/converters/geometryConverters.py
  armi/tests/test_runLog.py
  doc/.templates/breadcrumbs.html
  doc/blog/2020-09-17_3d_visualization.rst
  doc/blog/index.rst
  doc/conf.py
  doc/index.rst
  doc/release/0.1.rst
  doc/release/0.2.rst
Labels: bug, documentation, cleanup
