Repository terrapower/armi, pull requests merged in 2021-08, with the labels that each got.

#377 Remove unused SINCE_LAST_DB_TRANSMISSION on the parameter definitions
  armi/bookkeeping/db/database3.py
  armi/reactor/parameters/__init__.py
  armi/reactor/parameters/parameterDefinitions.py
Labels: architecture, cleanup

#378 Add code to distribute parameter assigned state
  armi/mpiActions.py
  armi/reactor/composites.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/tests/test_mpiActions.py
Labels: enhancement

#380 Cleanup - Unused Imports and settingsValidation tests
  .coveragerc
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/tests/test_databaseInterface.py
  armi/bookkeeping/tests/test_report.py
  armi/cli/__init__.py
  armi/cli/reportsEntryPoint.py
  armi/cli/runSuite.py
  armi/interfaces.py
  armi/nuclearDataIO/tests/test_xsCollections.py
  armi/nuclearDataIO/tests/test_xsNuclides.py
  armi/operators/settingsValidation.py
  armi/operators/tests/test_inspectors.py
  armi/physics/neutronics/const.py
  armi/reactor/blockParameters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_parameters.py
  armi/settings/caseSettings.py
  armi/settings/settingsIO.py
  armi/tests/test_context.py
  armi/tests/test_mpiActions.py
  armi/utils/dochelpers.py
  armi/utils/dynamicImporter.py
  armi/utils/plotting.py
  armi/utils/tests/test_pathTools.py
  armi/utils/tests/test_plotting.py
  armi/utils/textProcessors.py
Labels: cleanup

#382 Fixing infinite loop in interpreter
  armi/settings/settingsIO.py
Labels: bug

#383 Various updates to runLog outputs to the standard output
  armi/cases/case.py
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/settings/fwSettings/globalSettings.py
  armi/utils/pathTools.py
Labels: bug, cleanup

#395 Converting snake_case to camelCase
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/utils/gridEditor.py
Labels: cleanup
