Repository terrapower/armi, pull requests merged in 2021-09, with the labels that each got.

#405 Protecting against calls to wiping entire directories
  armi/bookkeeping/mainInterface.py
  armi/cases/suite.py
  armi/cases/suiteBuilder.py
  armi/cases/tests/test_cases.py
  armi/context.py
  armi/operators/operator.py
  armi/utils/__init__.py
  armi/utils/directoryChangers.py
  armi/utils/outputCache.py
  armi/utils/pathTools.py
Labels: bug

#404 Using GitHub Actions to Auto-Deploy Docs
  .github/workflows/docs.yaml
  .gitignore
  doc/requirements-docs.txt
  doc/user/user_install.rst
  tox.ini
Labels: documentation

#419 Added extension to profiling instructions
  doc/developer/profiling.rst
Labels: bug, documentation

#418 Fixing the example gallery in our docs.
  .github/workflows/docs.yaml
  .gitignore
  doc/conf.py
  doc/gallery-src/analysis/run_blockMcnpMaterialCard.py
  doc/gallery-src/analysis/run_hexReactorToRZ.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/gallery-src/framework/run_programmaticReactorDefinition.py
  doc/gallery-src/framework/run_reactorFacemap.py
Labels: bug, documentation

#421 Fixing missing docstring in the auto docs
  armi/materials/thoriumOxide.py
Labels: documentation, cleanup
