Repository terrapower/armi, pull requests merged in 2021-11, with the labels that each got.

#465 Reverting changes to snapshot interface
  armi/bookkeeping/snapshotInterface.py
Labels: enhancement, cleanup

#476 Switching form a Setting deepcopy to a copy
  armi/bookkeeping/db/tests/test_database3.py
  armi/settings/caseSettings.py
  armi/settings/tests/test_settings.py
Labels: enhancement

#480 Release v0.2.0
  armi/meta.py
  doc/release/0.1.rst
  doc/release/0.2.rst
  doc/release/index.rst
  setup.py
Labels: enhancement

#482 Update docs to remove sphinx warnings
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/newReportUtils.py
  armi/bookkeeping/plotting.py
  armi/bookkeeping/visualization/vtk.py
  armi/cases/case.py
  armi/cases/inputModifiers/inputModifiers.py
  armi/cli/modify.py
  armi/mpiActions.py
  armi/nucDirectory/nuclideBases.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/components/__init__.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/composites.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/geometry.py
  armi/reactor/grids.py
  armi/reactor/parameters/exceptions.py
  armi/reactor/parameters/resolveCollections.py
  armi/reactor/reactors.py
  armi/runLog.py
  armi/utils/codeTiming.py
  armi/utils/gridEditor.py
  armi/utils/plotting.py
  doc/developer/guide.rst
  doc/index.rst
  doc/tutorials/making_your_first_app.rst
  doc/user/user_install.rst
Labels: documentation, cleanup

#483 Adding Instructions on How To Release ARMI
  doc/conf.py
  doc/developer/making_armi_based_apps.rst
  doc/developer/tooling.rst
Labels: documentation

#484 FIXING Sphinx doc build errors
  doc/conf.py
  doc/requirements-docs.txt
Labels: bug, documentation

#488 Replace outdated table with API doc.
  doc/user/inputs/fuel_management.rst
Labels: documentation

#489 Update `findAssembly`'s docstring
  armi/physics/fuelCycle/fuelHandlers.py
Labels: documentation, cleanup

#491 Realistically, we have not been supporting Python 3.6
  setup.py
Labels: enhancement, cleanup
