Repository terrapower/armi, pull requests merged in 2022-11, with the labels that each got.

#955 Splitting 3 database3.py classes into 3 files
  armi/bookkeeping/__init__.py
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/db/tests/test_layout.py
  armi/nuclearDataIO/cccc/tests/test_pmatrx.py
  doc/release/0.2.rst
Labels: architecture

#958 Map pin quantities
  armi/physics/neutronics/parameters.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/parameters/parameterDefinitions.py
  doc/release/0.2.rst
Labels: feature request

#959 Use r.core.axialMesh() for uniform mesh.
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  doc/release/0.2.rst
Labels: bug

#952 Organize output files by cycle/node.
  armi/bookkeeping/snapshotInterface.py
  armi/physics/executers.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/settings/fwSettings/globalSettings.py
  armi/utils/directoryChangers.py
  armi/utils/directoryChangersMpi.py
  armi/utils/tests/test_directoryChangers.py
  doc/release/0.2.rst
  doc/user/outputs/index.rst
Labels: feature request

#961 Added reactor operator back into geometry converted reactor for model…
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/reactor/converters/uniformMesh.py
Labels: feature request

#962 Moving FuelHandler Algorithms to separate files
  armi/physics/fuelCycle/assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/fuelHandlerFactory.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/hexAssemblyFuelMgmtUtils.py
  armi/physics/fuelCycle/tests/test_assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/fuelCycle/tests/test_hexAssemblyFuelMgmtUtils.py
  doc/release/0.2.rst
Labels: architecture, cleanup

#968 Cleaning up defunct comments
  armi/nuclearDataIO/cccc/nhflux.py
  armi/physics/neutronics/parameters.py
Labels: documentation, cleanup

#981 Removing unused TH parameters
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/reactorParameters.py
Labels: cleanup

#967 UserPlugins can't define Parameters
  armi/plugins.py
  doc/tutorials/making_your_first_app.rst
Labels: documentation, cleanup

#986 Removing unused ARMI Parameters
  armi/physics/neutronics/parameters.py
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/blockParameters.py
  armi/reactor/reactorParameters.py
Labels: cleanup, feature request

#988 Removing unused mech Parameters
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
Labels: enhancement, cleanup

#989 Removing unused SASSYS Parameters
  armi/reactor/reactorParameters.py
Labels: cleanup

#987 Removing unused (and redundant) Parameter Category
  armi/reactor/parameters/parameterDefinitions.py
Labels: enhancement, cleanup

#997 Removing unused Parameters
  armi/physics/fuelPerformance/parameters.py
  armi/physics/neutronics/parameters.py
  armi/reactor/blockParameters.py
  armi/reactor/reactorParameters.py
Labels: cleanup

#980 Bug fix for core mesh params + nonUniformAssems
  armi/reactor/reactors.py
  doc/release/0.2.rst
Labels: bug
