Repository terrapower/armi, pull requests merged in 2022-07, with the labels that each got.

#743 Fixed broken error message in HexGrid
  armi/reactor/grids.py
  armi/reactor/tests/test_grids.py
Labels: bug

#744 Removing unused code
  armi/bookkeeping/__init__.py
  armi/bookkeeping/db/__init__.py
  armi/cli/copyDB.py
  armi/cli/tests/test_runEntryPoint.py
  armi/materials/tests/test_materials.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
Labels: cleanup, testing

#746 Cleanup composite.getComponent
  armi/operators/tests/test_operators.py
  armi/reactor/composites.py
  armi/reactor/tests/test_composites.py
Labels: cleanup

#748 Making component naming conventions more clear
  armi/reactor/components/component.py
  armi/reactor/tests/test_components.py
  doc/developer/tooling.rst
  doc/user/inputs/blueprints.rst
Labels: documentation

#752 Removing unused variables
  armi/cases/tests/test_cases.py
  armi/cli/reportsEntryPoint.py
  armi/materials/tests/test_materials.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/physics/neutronics/tests/test_crossSectionTable.py
  armi/physics/neutronics/tests/test_macroXSGenerationInterface.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/reactor/blueprints/tests/test_materialModifications.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settings.py
  armi/utils/directoryChangers.py
Labels: cleanup

#754 Removing unused method arguments
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/tests/test_memoryProfiler.py
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  armi/cli/checkInputs.py
  armi/materials/material.py
  armi/mpiActions.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/components/__init__.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/grids.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_reactors.py
  armi/scripts/migration/m0_1_0_newDbFormat.py
  armi/utils/__init__.py
  armi/utils/pathTools.py
Labels: cleanup

#756 Adding `load pad` flag
  armi/reactor/flags.py
Labels: enhancement

#760 Fixing broken Alloy200 methods
  armi/materials/alloy200.py
  armi/materials/material.py
  armi/materials/tests/test_materials.py
  armi/materials/uraniumOxide.py
  doc/release/0.2.rst
Labels: bug

#758 Fix setting of `core.p.power` in zero-burnup cases
  armi/operators/operator.py
Labels: bug

#723 Adding new User Plugin feature
  armi/apps.py
  armi/physics/fuelCycle/__init__.py
  armi/plugins.py
  armi/resources/coveragerc
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  armi/tests/test_apps.py
  armi/tests/test_user_plugins.py
  doc/release/0.2.rst
  doc/tutorials/making_your_first_app.rst
Labels: feature request

#765 Fixing removeAssembliesInRing for circular hex reactors
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
Labels: bug

#762 Making min/max temperatures for Material curves more discoverable
  armi/materials/alloy200.py
  armi/materials/b4c.py
  armi/materials/be9.py
  armi/materials/californium.py
  armi/materials/copper.py
  armi/materials/cs.py
  armi/materials/custom.py
  armi/materials/graphite.py
  armi/materials/hastelloyN.py
  armi/materials/ht9.py
  armi/materials/inconel600.py
  armi/materials/inconel625.py
  armi/materials/inconel800.py
  armi/materials/inconelX750.py
  armi/materials/lead.py
  armi/materials/leadBismuth.py
  armi/materials/lithium.py
  armi/materials/magnesium.py
  armi/materials/material.py
  armi/materials/mgO.py
  armi/materials/molybdenum.py
  armi/materials/mox.py
  armi/materials/potassium.py
  armi/materials/scandiumOxide.py
  armi/materials/siC.py
  armi/materials/sodium.py
  armi/materials/sodiumChloride.py
  armi/materials/sulfur.py
  armi/materials/tZM.py
  armi/materials/tantalum.py
  armi/materials/tests/test_b4c.py
  armi/materials/tests/test_be9.py
  armi/materials/tests/test_graphite.py
  armi/materials/tests/test_lithium.py
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_sic.py
  armi/materials/tests/test_sulfur.py
  armi/materials/tests/test_thoriumOxide.py
  armi/materials/tests/test_uZr.py
  armi/materials/tests/test_water.py
  armi/materials/thU.py
  armi/materials/thorium.py
  armi/materials/thoriumOxide.py
  armi/materials/uThZr.py
  armi/materials/uranium.py
  armi/materials/uraniumOxide.py
  armi/materials/void.py
  armi/materials/water.py
  armi/materials/yttriumOxide.py
  armi/materials/zincOxide.py
  armi/materials/zr.py
  doc/release/0.2.rst
Labels: enhancement, feature request

#771 Fixing error in docs - MAX_Z bounds were not enforced
  doc/gallery-src/framework/run_materials.py
Labels: bug

#773 Clarifying the inputs of plotAssemblyTypes
  armi/utils/plotting.py
  armi/utils/tests/test_plotting.py
Labels: documentation

#779 Updating case compare to match new signature
  armi/cases/suite.py
Labels: bug

#775 Update 1D block converter to prevent negative area components.
  armi/reactor/converters/blockConverters.py
  armi/reactor/converters/tests/test_blockConverter.py
Labels: bug

#781 Constrain jinja2 version
  doc/requirements-docs.txt
Labels: enhancement

#782 Moving to Python 3.10 as default
  .github/workflows/black.yaml
  .github/workflows/coverage.yaml
  .github/workflows/validatemanifest.yaml
  .github/workflows/wintests.yaml
Labels: enhancement

#783 fix snap list for blueprints assemblies
  armi/bookkeeping/db/tests/test_database3.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
Labels: bug, enhancement

#784 Adding a 'good PR' guide to the Docs
  .github/pull_request_template.md
  doc/developer/standards_and_practices.rst
  doc/developer/tooling.rst
Labels: documentation

#789 Adding unit tests for compareDB utils
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/reactor/converters/geometryConverters.py
Labels: cleanup, testing

#794 Improving HistoryTracker code coverage
  armi/bookkeeping/historyTracker.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/geometry.py
  pylintrc
Labels: cleanup, testing

#798 Cleaning up UserPlugins
  armi/apps.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/operators/tests/test_operators.py
  armi/tests/test_plugins.py
  armi/tests/test_user_plugins.py
  armi/utils/pathTools.py
  armi/utils/tests/test_pathTools.py
  doc/tutorials/making_your_first_app.rst
Labels: bug, cleanup
