Repository terrapower/armi, pull requests merged in 2022-06, with the labels that each got.

#693 Update to `armi.tests.detailedAxialExpansion`
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/tests/detailedAxialExpansion/refSmallCoreGrid.yaml
  armi/tests/detailedAxialExpansion/refSmallReactor.yaml
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
Labels: testing

#696 MANIFEST.ini update for PR #693
  MANIFEST.in
Labels: enhancement

#697 Allow jumpRingTo to be equal to 1
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
Labels: enhancement

#700 Adding CI validation for the MANIFEST.in
  .github/workflows/validatemanifest.py
  .github/workflows/validatemanifest.yaml
  MANIFEST.in
  armi/bookkeeping/tests/test_historyTracker.py
  tox.ini
Labels: enhancement

#704 Fixing bug in memory profiler
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/tests/test_memoryProfiler.py
  armi/tests/refTestCartesian.yaml
  doc/release/0.2.rst
  setup.py
Labels: bug

#689 Fix MPI hanging bug.
  armi/bookkeeping/mainInterface.py
  armi/context.py
  armi/mpiActions.py
  armi/operators/operator.py
  armi/tests/armiRun.yaml
  armi/tests/test_mpiFeatures.py
  armi/utils/directoryChangers.py
  armi/utils/outputCache.py
  armi/utils/pathTools.py
  armi/utils/tests/test_pathTools.py
Labels: bug, enhancement

#708 Upgrade grid editor to work with Python 3.10.
  armi/utils/gridEditor.py
Labels: enhancement

#709 Update unit tests to also pass in Python 3.10
  armi/settings/tests/test_settings.py
  armi/tests/tutorials/c5g7-blueprints.yaml
  armi/utils/tests/test_gridGui.py
Labels: enhancement

#712 Renaming default branch to main
  .github/workflows/docs.yaml
  CONTRIBUTING.md
  README.rst
  doc/conf.py
  doc/developer/tooling.rst
  doc/release/0.2.rst
  doc/user/user_install.rst
Labels: enhancement, cleanup, feature request

#707 update getPinToDuctGap to ignore holedHex
  armi/reactor/blocks.py
Labels: enhancement

#714 Add a warning about excessive plotting
  armi/utils/plotting.py
Labels: documentation, cleanup

#716 Adding Python 3.10 to our GH Actions unit testing
  .github/workflows/unittests.yaml
  .github/workflows/wintests.yaml
  doc/conf.py
  tox.ini
Labels: enhancement, testing

#717 `updateGlobalAssemblyNum` called twice during `loadState`
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
Labels: enhancement

#719 Plotting should really be in the utils folder
  armi/bookkeeping/historyTracker.py
  armi/bookkeeping/newReports.py
  armi/bookkeeping/report/reportInterface.py
  armi/nuclearDataIO/cccc/rtflux.py
  armi/nuclearDataIO/xsLibraries.py
  armi/reactor/blocks.py
  armi/utils/plotting.py
  armi/utils/reportPlotting.py
  armi/utils/tests/test_custom_exceptions.py
  armi/utils/tests/test_directoryChangers.py
  armi/utils/tests/test_outputCache.py
  armi/utils/tests/test_reportPlotting.py
  armi/utils/tests/test_utils.py
Labels: enhancement, cleanup

#737 Removing defunct "geom" reference
  armi/bookkeeping/mainInterface.py
  armi/reactor/reactors.py
Labels: bug

#736 Notes parameter
  armi/reactor/assemblyParameters.py
  armi/reactor/tests/test_assemblies.py
Labels: feature request

#738 Removing GH codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: cleanup

#733 Setting the trackAssems default to False
  armi/apps.py
  armi/operators/snapshots.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/tests/test_settings.py
  armi/utils/dynamicImporter.py
  doc/release/0.2.rst
Labels: enhancement

#713 Uniform mesh converter update
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
Labels: enhancement

#699 Remove pinPowers parameter from block module
  armi/physics/neutronics/parameters.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: cleanup

#727 Fix centering in the Cartesian test case.
  armi/tests/refSmallCartesian.yaml
Labels: documentation
