Repository terrapower/armi, pull requests merged in 2022-03, with the labels that each got.

#586 Remove PyYaml Dependency
  README.rst
  armi/bookkeeping/db/database3.py
  armi/cases/inputModifiers/tests/test_inputModifiers.py
  armi/nucDirectory/nuclideBases.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/reactor/blocks.py
  armi/reactor/reactors.py
  armi/utils/tests/test_outputCache.py
  armi/utils/textProcessors.py
  doc/release/0.2.rst
  setup.py
  tox.ini
Labels: cleanup

#590 Tracking ARMI Requirements
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cases/tests/test_suiteBuilder.py
  armi/cli/__init__.py
  armi/nuclearDataIO/cccc/tests/test_nhflux.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/settings.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/grids.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_grids.py
  armi/reactor/tests/test_reactors.py
  armi/settings/tests/old_xml_settings_input.xml
  armi/utils/__init__.py
  armi/utils/iterables.py
  armi/utils/tests/test_utils.py
  doc/conf.py
  doc/developer/tooling.rst
  doc/index.rst
  doc/requirements-docs.txt
  doc/requirements/index.rst
  doc/requirements/srsd.rst
Labels: documentation, enhancement

#593 Application permissive configure fix
  armi/__init__.py
Labels: bug

#594 Removing defunct code from historyTracker Interface
  armi/bookkeeping/historyTracker.py
Labels: cleanup

#592 Adding coding standards and practices to Docs
  armi/reactor/components/__init__.py
  doc/developer/parallel_coding.rst
  doc/developer/standards_and_practices.rst
Labels: documentation

#598 Adding options to Settings Report
  doc/user/inputs/settings_report.rst
Labels: documentation

#601 Fixing xsLibraries docstring
  armi/nuclearDataIO/xsLibraries.py
Labels: documentation

#600 Unshaped component
  armi/reactor/components/__init__.py
  armi/reactor/tests/test_components.py
Labels: enhancement

#607 Fixing _fluxSwapParam for NumPy arrays
  armi/utils/mathematics.py
  armi/utils/tests/test_mathematics.py
Labels: bug

#604 remove extraneous `mpicov` arg from tox.ini envlist
  tox.ini
Labels: cleanup

#610 Minor language cleanup in new standards and practices.
  doc/developer/standards_and_practices.rst
Labels: documentation
