Repository terrapower/armi, pull requests merged in 2022-12, with the labels that each got.

#1004 Updating Ubuntu in GH workflows to fix MPI
  .github/workflows/black.yaml
  .github/workflows/coverage.yaml
  .github/workflows/docs.yaml
  .github/workflows/unittests.yaml
  .github/workflows/validatemanifest.yaml
Labels: bug, documentation, testing

#1001 Moving hyper-specific TH parameters out of ARMI
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
Labels: cleanup

#1015 Adding util function to test for depletion
  armi/utils/__init__.py
  armi/utils/tests/test_utils.py
Labels: feature request

#1014 Fixing bug with fp interface not in geomConverter
  armi/reactor/converters/geometryConverters.py
Labels: bug

#1005 Fix DB write out for coupling
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  doc/release/0.2.rst
Labels: bug

#992 Fix numerical diffusion in uniformMesh converter
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/parameters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/parameters/parameterDefinitions.py
  doc/release/0.2.rst
Labels: bug

#1009 added modern RZ theta unittest for ARMI
  armi/reactor/tests/test_rz_reactors.py
  armi/tests/Godiva-blueprints.yaml
  armi/tests/Godiva.armi.unittest.yaml
Labels: feature request

#1031 Removing duplicate GitHub Actions runs
  .github/workflows/black.yaml
  .github/workflows/coverage.yaml
  .github/workflows/licensechecker.yaml
  .github/workflows/unittests.yaml
  .github/workflows/validatemanifest.yaml
  .github/workflows/wintests.yaml
Labels: testing, optimization

#1027 Air
  armi/materials/air.py
  armi/materials/tests/test_air.py
  armi/tests/Godiva-blueprints.yaml
Labels: feature request

#1035 Freezing the maximum NumPy version to 1.23.5
  .github/workflows/coverage.yaml
  doc/release/0.2.rst
  requirements-testing.txt
  requirements.txt
  setup.py
Labels: bug

#998 Extension of the framework nuclides
  MANIFEST.in
  armi/_bootstrap.py
  armi/cases/case.py
  armi/materials/material.py
  armi/materials/tests/test_lithium.py
  armi/nucDirectory/__init__.py
  armi/nucDirectory/elements.py
  armi/nucDirectory/nucDir.py
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/tests/test_elements.py
  armi/nucDirectory/tests/test_nucDirectory.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/nucDirectory/tests/test_thermalScattering.py
  armi/nucDirectory/tests/test_transmutations.py
  armi/nucDirectory/thermalScattering.py
  armi/nucDirectory/transmutations.py
  armi/nuclearDataIO/cccc/dlayxs.py
  armi/nuclearDataIO/ripl.py
  armi/nuclearDataIO/tests/longLivedRipleData.dat
  armi/nuclearDataIO/tests/test_ripl.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/tests/test_xsNuclides.py
  armi/nuclearDataIO/tests/z036.dat
  armi/nuclearDataIO/xsNuclides.py
  armi/physics/executers.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/neutronics/fissionProductModel/tests/test_lumpedFissionProduct.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/blueprints/tests/test_componentBlueprint.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/tests/test_reactors.py
  armi/resources/burn-chain.yaml
  armi/resources/elements.dat
  armi/resources/endf_mf_nums.txt
  armi/resources/endf_mt_nums.txt
  armi/resources/mc2Nuclides.yaml
  armi/resources/mcc-nuclides.yaml
  armi/resources/nuclides.dat
  armi/resources/referenceFissionProducts.dat
  armi/resources/ripl-abundance.dat
  armi/resources/ripl-mass-frdm95.dat
  armi/resources/thermal_scattering_labels.txt
  armi/settings/fwSettings/globalSettings.py
  armi/utils/tests/test_textProcessors.py
  armi/utils/units.py
  doc/release/0.2.rst
  doc/tutorials/materials_demo.ipynb
  doc/tutorials/nuclide_demo.ipynb
  doc/user/inputs/blueprints.rst
  doc/user/user_install.rst
Labels: enhancement

#1041 Remove `refType` from settings files
  armi/tests/armiRun.yaml
  armi/tests/refTestCartesian.yaml
Labels: cleanup

#1045 Reverting GitHub Actions change - adding in duplicate jobs
  .github/workflows/black.yaml
  .github/workflows/licensechecker.yaml
  .github/workflows/unittests.yaml
  .github/workflows/validatemanifest.yaml
  .github/workflows/wintests.yaml
Labels: testing

#1046 Bug fix for global material namespace order
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  doc/release/0.2.rst
Labels: bug

#1040 Bug fix to correct difference tabulation
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
Labels: bug

#1022 Explicit Fission Product Modeling
  armi/cases/case.py
  armi/nucDirectory/nucDir.py
  armi/nucDirectory/tests/test_nucDirectory.py
  armi/operators/settingsValidation.py
  armi/physics/fuelPerformance/executers.py
  armi/physics/fuelPerformance/parameters.py
  armi/physics/fuelPerformance/settings.py
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/fissionProductModel/__init__.py
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/fissionProductModelSettings.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/tests/test_lumpedFissionProduct.py
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/physics/neutronics/tests/test_cross_section_manager.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/tests/test_assemblies.py
  armi/resources/mcc-nuclides.yaml
  armi/resources/referenceFissionProducts.dat
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  doc/release/0.2.rst
Labels: bug, enhancement

#1051 Adding some testing to our snapshots
  armi/operators/tests/test_operatorSnapshots.py
Labels: testing

#1053 Removing unused getMassFrac parameters
  armi/materials/material.py
Labels: cleanup
