Repository terrapower/armi, pull requests merged in 2022-04, with the labels that each got.

#612 Removing support for XML Settings files
  .github/workflows/black.yaml
  MANIFEST.in
  armi/cli/compareCases.py
  armi/cli/database.py
  armi/cli/migrateInputs.py
  armi/operators/settingsValidation.py
  armi/scripts/migration/__init__.py
  armi/scripts/migration/m0_1_0_settings.py
  armi/settings/__init__.py
  armi/settings/caseSettings.py
  armi/settings/setting.py
  armi/settings/settingsIO.py
  armi/settings/tests/old_xml_settings_input.xml
  armi/settings/tests/test_settings.py
  armi/settings/tests/test_settingsIO.py
  armi/utils/customExceptions.py
  pytest.ini
  setup.py
Labels: architecture, cleanup

#625 Adding MPI tests to code coverage
  .coveragerc
  .github/workflows/coverage.yaml
  tox.ini
Labels: enhancement, testing

#624 Making the app version more available
  armi/__init__.py
  armi/apps.py
  armi/bookkeeping/tests/test_report.py
  armi/cases/inputModifiers/tests/test_inputModifiers.py
  armi/cli/__init__.py
  armi/cli/tests/test_runEntryPoint.py
  armi/cli/tests/test_runSuite.py
  armi/tests/test_apps.py
  armi/utils/tests/test_dochelpers.py
Labels: feature request

#615 Fixing assembly number issue in DB Load
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/tests/test_databaseInterface.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  doc/developer/standards_and_practices.rst
  doc/release/0.2.rst
Labels: bug

#626 Removing bare "import armi" statements
  armi/__init__.py
  armi/__main__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/newReports.py
  armi/bookkeeping/report/html.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/tests/test_report.py
  armi/cases/case.py
  armi/cli/__init__.py
  armi/cli/database.py
  armi/cli/reportsEntryPoint.py
  armi/mpiActions.py
  armi/nucDirectory/nuclideBases.py
  armi/operators/__init__.py
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  armi/operators/settingsValidation.py
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/macroXSGenerationInterface.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/composites.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_parameters.py
  armi/settings/caseSettings.py
  armi/settings/tests/test_settings.py
  armi/settings/tests/test_settingsIO.py
  armi/tests/__init__.py
  armi/tests/test_apps.py
  armi/tests/test_cartesian.py
  armi/tests/test_mpiActions.py
  armi/tests/test_mpiFeatures.py
  armi/tests/test_plugins.py
  armi/utils/__init__.py
  armi/utils/directoryChangers.py
  armi/utils/tests/test_custom_exceptions.py
  doc/conf.py
  doc/release/0.2.rst
Labels: cleanup

#628 Removing inherited docstrings from Docs
  doc/conf.py
Labels: documentation

#631 Improving Code Coverage
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/tests/test_report.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_parameters.py
Labels: testing

#632 Update DoseResultsMapper.apply() to accept blockList
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
Labels: enhancement

#634 Improving Code Coverage (and doing cleanup)
  .gitignore
  README.rst
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/nuclearDataIO/tests/library-file-generation/mc2v2-dlayxs.inp
  armi/nuclearDataIO/tests/library-file-generation/mc2v3-AA.inp
  armi/nuclearDataIO/tests/library-file-generation/mc2v3-AB.inp
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/tests/test_zones.py
  armi/settings/caseSettings.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settingsIO.py
  armi/utils/dynamicImporter.py
  doc/developer/reports.rst
  doc/developer/standards_and_practices.rst
  doc/user/accessingEntryPoints.rst
Labels: cleanup, testing

#638 Improving Code Coverage
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/tests/test_databaseInterface.py
  armi/bookkeeping/tests/test_report.py
  armi/cases/tests/test_suiteBuilder.py
  armi/cli/checkInputs.py
  armi/cli/tests/test_runEntryPoint.py
  armi/materials/alloy200.py
  armi/materials/mgO.py
  armi/materials/tests/test_b4c.py
  armi/materials/tests/test_lithium.py
  armi/materials/tests/test_materials.py
  armi/nucDirectory/tests/test_thermalScattering.py
  armi/nuclearDataIO/cccc/tests/test_dlayxs.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/physics/neutronics/diffIsotxs.py
  armi/physics/neutronics/fissionProductModel/tests/test_lumpedFissionProduct.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/reactor/composites.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_geometry.py
  armi/reactor/tests/test_grids.py
  armi/reactor/tests/test_reactors.py
  armi/scripts/migration/tests/test_m0_1_6_locationLabels.py
  armi/settings/tests/test_settings.py
  armi/utils/tests/test_textProcessors.py
Labels: testing

#643 Update `loadTestReactor` docstring
  armi/reactor/tests/test_reactors.py
Labels: documentation

#644 Make description of `cycleLength` parameter consistent with `availabilityFactor`
  armi/reactor/reactorParameters.py
Labels: documentation

#646 Increasing the flexibility of plotAssemblyTypes
  .gitattributes
  armi/tests/armiRun
  armi/utils/plotting.py
  armi/utils/tests/test_plotting.py
Labels: enhancement

#647 Fixing bug in addDummyNuclidesToLibrary
  README.rst
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/tests/test_gamiso.py
  armi/nuclearDataIO/xsNuclides.py
  armi/utils/codeTiming.py
  armi/utils/iterables.py
Labels: bug
