Repository terrapower/armi, pull requests merged in 2022-08, with the labels that each got.

#802 copyInterfaceInputs bug fix
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  doc/release/0.2.rst
Labels: bug, help wanted

#787 Thermal expansion update
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
Labels: bug, testing

#777 Enable Users To Explicitly Specify Target Component for Axial Expansion
  armi/reactor/blocks.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
  doc/release/0.2.rst
Labels: enhancement

#804 Number density bug fix
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/components/component.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  doc/release/0.2.rst
Labels: bug

#797 Clean up axial expansion in core.processLoading for DB load
  armi/bookkeeping/db/database3.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/reactors.py
  doc/release/0.2.rst
Labels: bug, cleanup

#809 Add try/except around unpackSpecialData
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  doc/release/0.2.rst
Labels: cleanup

#814 Improved Code Coverage Database3
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/utils/tests/test_plotting.py
Labels: cleanup, testing

#816 rewrite of copyInterfaceInputs
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  doc/release/0.2.rst
Labels: cleanup

#828 Removing Defunct Docs
  doc/user/assorted_guide.rst
  doc/user/inputs/fuel_management.rst
Labels: documentation, cleanup

#829 `startCycle` clarification
  armi/operators/settingsValidation.py
  armi/settings/fwSettings/globalSettings.py
Labels: documentation, cleanup

#665 Update stationary block methods
  armi/bookkeeping/historyTracker.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/settings/fwSettings/globalSettings.py
  armi/tests/test_mpiFeatures.py
  doc/release/0.2.rst
Labels: feature request

#831 Update `removeAssembly()` docstring formatting
  armi/reactor/reactors.py
Labels: documentation, cleanup

#836 Fixing UserPlugins - Save the Interface Stack
  armi/__init__.py
  armi/apps.py
  armi/tests/test_apps.py
  armi/tests/test_user_plugins.py
Labels: bug, cleanup

#837 Resolve unit test coverage for axialExpansionChanger
  armi/reactor/converters/tests/test_axialExpansionChanger.py
Labels: testing

#835 Remove point class
  armi/physics/neutronics/parameters.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: cleanup

#841 Component initial denisty
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/components/component.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  doc/release/0.2.rst
Labels: bug

#799 Parameter mapping fix in the uniform mesh converter.
  armi/nuclearDataIO/xsLibraries.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/parameters.py
  armi/reactor/converters/blockConverters.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactorParameters.py
  armi/reactor/reactors.py
  doc/release/0.2.rst
Labels: bug, cleanup, feature request

#845 Improve Flexibility Of Component Temp Mapping + Bug Fix With Radial NDens Update
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
Labels: bug, feature request

#849 Update block point parameters so that corner and edge data are separate
  armi/physics/neutronics/parameters.py
Labels: architecture, feature request

#854 Uniform mesh refactor for single assembly number density and parameter data mapping
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  doc/release/0.2.rst
Labels: enhancement, architecture

#860 Fixing Component density to agree with 3D density
  armi/materials/zr.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/components/component.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
Labels: bug

#834 Fixing broken returns
  armi/bookkeeping/db/factory.py
  armi/bookkeeping/newReportUtils.py
  armi/bookkeeping/report/data.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cli/database.py
  armi/context.py
  armi/materials/zr.py
  armi/mpiActions.py
  armi/nucDirectory/nucDir.py
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/plugins.py
  armi/reactor/assemblyLists.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/composites.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/geometry.py
  armi/reactor/grids.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_geometry.py
  armi/reactor/tests/test_grids.py
  armi/scripts/migration/m0_1_6_locationLabels.py
  armi/tests/test_mpiFeatures.py
  armi/utils/__init__.py
  armi/utils/codeTiming.py
  armi/utils/gridEditor.py
Labels: bug
