Repository terrapower/armi, pull requests merged in 2022-05, with the labels that each got.

#650 updating `class Block` constructor and docstring
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_assemblies.py
Labels: documentation, testing

#652 Fixing a typo in gamiso.py
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/tests/test_gamiso.py
Labels: bug

#606 Assembly Level Axial Expansion Prototype
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/meshConverters.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_meshConverters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_reactors.py
Labels: feature request

#613 Update control rod parameters and generalize the neutronics mesh converter to copy all multi-group results.
  .gitignore
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/assemblies.py
  armi/reactor/assemblyParameters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactorParameters.py
  armi/reactor/tests/test_assemblies.py
Labels: enhancement

#655 updating docstring for applicable assembly-types
  armi/reactor/converters/axialExpansionChanger.py
Labels: documentation

#654 Move getWettedPerimeter to HexBlock
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  armi/tests/test_apps.py
  doc/release/0.2.rst
Labels: bug

#620 Split fuelHandlers.py into multiple scripts
  armi/physics/fuelCycle/fuelHandlerFactory.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
Labels: architecture

#656 Cleaning up comments and adding some tests
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/reactor/blocks.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
Labels: cleanup

#658 Adding licenses into new FuelHandler files
  armi/physics/fuelCycle/fuelHandlerFactory.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
Labels: bug, documentation

#621 Removing Empty Log Dirs
  armi/context.py
  armi/reactor/tests/test_reactors.py
  armi/runLog.py
  armi/tests/test_context.py
  armi/tests/test_runLog.py
Labels: feature request

#663 Adding a deprecation warning for GeomFiles
  armi/reactor/systemLayoutInput.py
Labels: documentation

#664 Let's not delete a file inside a loop
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  armi/tests/test_mpiFeatures.py
  armi/utils/pathTools.py
  armi/utils/tests/test_pathTools.py
  doc/release/0.2.rst
Labels: enhancement, cleanup

#637 Upgrade the cycles inputs
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/mainInterface.py
  armi/bookkeeping/newReportUtils.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/snapshotInterface.py
  armi/bookkeeping/tests/test_databaseInterface.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/bookkeeping/tests/test_snapshot.py
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/operators/tests/test_inspectors.py
  armi/operators/tests/test_operators.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/macroXSGenerationInterface.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/reactorParameters.py
  armi/reactor/tests/test_reactors.py
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/tests/test_settings.py
  armi/tests/armiRun.yaml
  armi/utils/__init__.py
  armi/utils/mathematics.py
  armi/utils/tests/test_mathematics.py
  armi/utils/tests/test_utils.py
  doc/user/inputs/settings.rst
Labels: feature request

#666 Let's not delete a file inside a loop (v2)
  .github/workflows/wintests.yaml
  armi/bookkeeping/db/tests/test_database3.py
  armi/cases/tests/test_cases.py
  armi/context.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  armi/tests/test_mpiFeatures.py
  armi/utils/directoryChangers.py
  armi/utils/pathTools.py
  armi/utils/tests/test_pathTools.py
  doc/release/0.2.rst
Labels: enhancement, cleanup

#672 Cleanup may12
  .github/workflows/coverage.yaml
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  doc/developer/standards_and_practices.rst
Labels: documentation, cleanup, testing

#673 Cleaning up compareDatabases
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
Labels: documentation, testing

#674 Cycles upgrade fix
  armi/settings/fwSettings/globalSettings.py
Labels: bug

#675 Improving code coverage and removing unused imports
  README.rst
  armi/bookkeeping/historyTracker.py
  armi/cli/reportsEntryPoint.py
  armi/cli/tests/test_runEntryPoint.py
  armi/context.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
  armi/reactor/composites.py
  armi/reactor/tests/test_composites.py
  armi/settings/settingsIO.py
  armi/tests/test_apps.py
  armi/tests/test_mpiFeatures.py
  armi/tests/test_runLog.py
  armi/utils/gridEditor.py
  armi/utils/tests/test_utils.py
Labels: cleanup, testing

#670 Update/upgrade for component axial linkage
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/tests/test_components.py
Labels: enhancement, feature request

#657 add `inputHeightsConsideredHot` setting
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/components/component.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/settings/fwSettings/globalSettings.py
  armi/tests/detailedAxialExpansion/armiRun.yaml
  armi/tests/detailedAxialExpansion/refSmallReactor.yaml
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
Labels: testing

#678 Fix - Yamlize docstrings are being forcably inherited
  README.rst
  armi/tests/test_runLog.py
  doc/conf.py
Labels: bug, documentation

#677 Fix setting the target component in axialExpansion
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
Labels: enhancement

#682 Improving MemoryProfiler test coverage
  .gitignore
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/tests/test_report.py
  armi/bookkeeping/tests/test_databaseInterface.py
  armi/bookkeeping/tests/test_memoryProfiler.py
  armi/bookkeeping/tests/test_report.py
  armi/nucDirectory/tests/test_elements.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
  armi/tests/test_apps.py
  armi/tests/test_plugins.py
  armi/tests/test_runLog.py
  armi/utils/tests/test_flags.py
  armi/utils/tests/test_triangle.py
Labels: cleanup, testing

#681 Nhflux variant bug
  armi/nuclearDataIO/cccc/nhflux.py
  armi/nuclearDataIO/cccc/tests/fixtures/simple_hexz.nhflux.variant
  armi/nuclearDataIO/cccc/tests/test_nhflux.py
Labels: bug

#683 Update `MpiDirectoryChanger` docstring
  armi/utils/directoryChangersMpi.py
Labels: documentation

#685 Assorted cleanup and bug fixes
  MANIFEST.in
  armi/bookkeeping/mainInterface.py
  armi/context.py
  armi/interfaces.py
  armi/operators/operator.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/runLog.py
  armi/utils/directoryChangers.py
  armi/utils/outputCache.py
  pylintrc
Labels: bug, cleanup

#686 Control rod assembly parameter renames
  armi/reactor/assemblyParameters.py
  doc/release/0.2.rst
Labels: enhancement
