Repository terrapower/armi, pull requests merged in 2022-01, with the labels that each got.

#521 MPI unit tests finally working again
  .coveragerc
  .github/workflows/coverage.yaml
  .github/workflows/unittests.yaml
  .gitignore
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/bookkeeping/tests/test_databaseInterface.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/bookkeeping/tests/test_memoryProfiler.py
  armi/interfaces.py
  armi/operators/tests/test_operators.py
  armi/reactor/tests/test_assemblies.py
  armi/tests/test_docs.py
  armi/tests/test_mpiActions.py
  armi/tests/test_mpiFeatures.py
  armi/tests/test_runLog.py
  tox.ini
Labels: enhancement, testing

#526 Removing duplicate versioning strings
  armi/meta.py
  doc/developer/tooling.rst
  setup.py
Labels: enhancement, cleanup

#534 Fixing the Setting copy to also copy non-default values.
  armi/meta.py
  armi/settings/setting.py
  armi/settings/tests/test_settings.py
  doc/release/0.2.rst
Labels: bug

#539 Updates to fix latex build of docs.
  README.rst
  armi/reactor/blocks.py
  armi/reactor/grids.py
  doc/.static/not-through-center.png
  doc/.static/through-center.png
  doc/user/accessingEntryPoints.rst
Labels: documentation

#531 Improving Type Hinting
  armi/__init__.py
  armi/context.py
  armi/materials/b4c.py
  armi/materials/material.py
  armi/materials/uranium.py
  armi/materials/uraniumOxide.py
  armi/materials/water.py
  armi/physics/executers.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/utils/__init__.py
  armi/utils/triangle.py
Labels: documentation, enhancement, cleanup

#543 Fix add option
  armi/meta.py
  armi/settings/setting.py
  armi/settings/tests/test_settings.py
  doc/release/0.2.rst
Labels: bug

#525 Add component group capabilities
  armi/bookkeeping/db/database3.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/components/__init__.py
  armi/reactor/components/component.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/composites.py
  armi/reactor/converters/blockConverters.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/tests/__init__.py
  doc/user/inputs/blueprints.rst
Labels: architecture

#548 `ThoriumOxide` upgrades
  armi/materials/tests/test_thoriumOxide.py
  armi/materials/thoriumOxide.py
  armi/materials/uraniumOxide.py
Labels: enhancement

#549 Adding good commit message practices
  .github/pull_request_template.md
  doc/developer/tooling.rst
Labels: enhancement

#551 Upgrading sphinx to bipass logging problems
  armi/runLog.py
  doc/conf.py
  doc/developer/tooling.rst
  doc/gallery-src/analysis/run_blockMcnpMaterialCard.py
  doc/gallery-src/analysis/run_hexBlockToRZConversion.py
  doc/gallery-src/analysis/run_hexReactorToRZ.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/gallery-src/framework/run_programmaticReactorDefinition.py
  doc/gallery-src/framework/run_reactorFacemap.py
  doc/requirements-docs.txt
  setup.py
Labels: documentation, enhancement
