Repository terrapower/armi, pull requests merged in 2022-09, with the labels that each got.

#863 Fixing HT9 density - to match reference
  armi/materials/ht9.py
Labels: bug

#869 Update the uniform mesher to check if the lower and upper mesh
  armi/reactor/converters/uniformMesh.py
Labels: bug

#867 Moving newReports into report package
  armi/bookkeeping/__init__.py
  armi/bookkeeping/report/newReportUtils.py
  armi/bookkeeping/report/newReports.py
  armi/bookkeeping/report/report.js
  armi/bookkeeping/report/styles.css
  armi/bookkeeping/report/tests/test_newReport.py
  armi/cli/reportsEntryPoint.py
  armi/physics/neutronics/reports.py
  doc/release/0.2.rst
Labels: architecture, cleanup

#866 Update nhflux reader to read higher-order VARIANT data
  armi/nuclearDataIO/cccc/nhflux.py
  armi/nuclearDataIO/cccc/tests/test_nhflux.py
  doc/release/0.2.rst
Labels: feature request

#873 Removing the unused / unnecessary DB baseclass
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/database3.py
Labels: architecture, cleanup

#868 Density3
  armi/materials/caH2.py
  armi/materials/californium.py
  armi/materials/cs.py
  armi/materials/hafnium.py
  armi/materials/inconel.py
  armi/materials/inconelPE16.py
  armi/materials/material.py
  armi/materials/mgO.py
  armi/materials/molybdenum.py
  armi/materials/nZ.py
  armi/materials/scandiumOxide.py
  armi/materials/sodiumChloride.py
  armi/materials/tZM.py
  armi/materials/tantalum.py
  armi/materials/tests/test_graphite.py
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_uZr.py
  armi/materials/thU.py
  armi/materials/thorium.py
  armi/materials/thoriumOxide.py
  armi/materials/uZr.py
  armi/materials/uraniumOxide.py
  armi/materials/yttriumOxide.py
  armi/utils/tests/test_densityTools.py
Labels: bug, architecture

#878 Reset caching on block components within uniform mesh converter
  armi/reactor/assemblies.py
  armi/reactor/converters/uniformMesh.py
Labels: bug

#883 Ensuring the code coverage won't fall below 80%
  .gitignore
  tox.ini
Labels: enhancement

#879 Allow treatment of non-uniform assemblies in the uniform mesh converter
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  doc/release/0.2.rst
Labels: enhancement

#885 Call `completeInitialLoading` after applying thermal expansion to the reactor core.
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  doc/release/0.2.rst
Labels: bug

#887 Fixing linear expansion of Zinc Oxide
  armi/materials/tests/test_materials.py
  armi/materials/zincOxide.py
Labels: bug

#881 Adding new Requirements to ARMI
  doc/requirements/index.rst
  doc/requirements/sdid.rst
  doc/requirements/srsd.rst
  doc/requirements/str.rst
Labels: documentation

#891 Fixing duplicate requirement name
  doc/requirements/srsd.rst
Labels: bug, documentation

#892 Add rootDir arg to modify CLI
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
Labels: enhancement

#890 Improving Code Coverage in Utils
  armi/utils/densityTools.py
  armi/utils/iterables.py
  armi/utils/outputCache.py
  armi/utils/tests/test_densityTools.py
  armi/utils/tests/test_outputCache.py
Labels: cleanup, testing

#900 Adding code coverage
  armi/cli/checkInputs.py
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
  armi/cli/tests/test_runSuite.py
  armi/interfaces.py
  armi/mpiActions.py
  armi/tests/test_mpiActions.py
  armi/utils/iterables.py
  armi/utils/tests/test_iterables.py
Labels: testing

#893 Fix non uniform assembly treatment
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
Labels: feature request

#899 Converting some methods to staticmethod
  armi/bookkeeping/db/database3.py
  armi/cli/__init__.py
  armi/cli/tests/test_runSuite.py
  armi/mpiActions.py
  armi/nuclearDataIO/nuclearFileMetadata.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/reactor/grids.py
  armi/reactor/tests/test_grids.py
Labels: cleanup

#898 Removing defunct settingsRules tools
  armi/operators/settingsValidation.py
  armi/physics/fuelCycle/__init__.py
  armi/physics/fuelCycle/settings.py
  armi/physics/fuelPerformance/settings.py
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/settings/settingsIO.py
  armi/settings/settingsRules.py
  doc/release/0.2.rst
Labels: architecture, cleanup

#902 Removing references to broken import path
  README.rst
  armi/bookkeeping/report/reportInterface.py
  armi/materials/__init__.py
  armi/nuclearDataIO/xsLibraries.py
  armi/physics/fuelCycle/fuelHandlerFactory.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/reactor/blocks.py
  armi/utils/units.py
Labels: cleanup

#906 Removing fictitious import
  armi/physics/fuelCycle/fuelHandlerFactory.py
  armi/utils/pathTools.py
Labels: cleanup

#901 Removing reference to r.o
  armi/bookkeeping/report/reportInterface.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/utils/reportPlotting.py
Labels: enhancement, cleanup

#909 Use b.core instead of b.r.core.
  armi/reactor/blocks.py
Labels: architecture

#912 Making Case.run more testable
  armi/cases/case.py
  armi/cases/tests/test_cases.py
Labels: cleanup, testing
