Repository terrapower/armi, pull requests merged in 2022-10, with the labels that each got.

#911 Fix burnup-dependent reaction rates
  armi/reactor/blocks.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  doc/release/0.2.rst
Labels: feature request

#915 Adding code coverage to report plotting
  armi/physics/neutronics/tests/test_macroXSGenerationInterface.py
  armi/utils/reportPlotting.py
  armi/utils/tests/test_reportPlotting.py
Labels: testing

#918 Fixing typo in docs for coupling
  doc/user/assorted_guide.rst
Labels: documentation

#917 Releasing ARMI v0.2.4
  armi/meta.py
  doc/release/0.2.rst
Labels: documentation

#919 Uniform mesh update for reaction rate calculations of non-uniform assemblies
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
Labels: enhancement

#926 Removing unused method dumpRestartData
  armi/operators/operator.py
Labels: cleanup

#928 Add the `detailedAxialExpansion` category to the fast flux parameter
  armi/physics/neutronics/parameters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  doc/release/0.2.rst
Labels: bug

#924 Add writer style option to SettingsWriter pt1
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
  armi/settings/caseSettings.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settings.py
  armi/settings/tests/test_settingsIO.py
  doc/release/0.2.rst
Labels: enhancement

#923 Remove deprecated coveragerc file
  .coveragerc
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  armi/context.py
  armi/resources/coveragerc
  doc/release/0.2.rst
Labels: cleanup

#929 Restore the db `_fullPath` upon close()
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
Labels: feature request

#922 Update the EntryPoint class to provide user feedback on required positional arguments
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/cli/checkInputs.py
  armi/cli/clone.py
  armi/cli/entryPoint.py
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
  armi/reactor/tests/test_reactors.py
  armi/tests/armiRun.yaml
  doc/release/0.2.rst
Labels: enhancement

#933 add ability to compute hydraulic diameter for unpinned HexBlock objects
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: feature request

#938 Zones overhaul updates
  armi/plugins.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_zones.py
  armi/reactor/zones.py
  armi/tests/test_user_plugins.py
Labels: enhancement, architecture

#937 Removing usages of get/setMasterCs in getDpaXs
  armi/cli/reportsEntryPoint.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/reactor/blocks.py
Labels: architecture, cleanup

#936 Allow case coverage to use user-supplied coverage config file
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  armi/settings/fwSettings/globalSettings.py
Labels: enhancement

#946 Removing two usages of getMasterCs
  armi/bookkeeping/report/data.py
  armi/bookkeeping/report/html.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
Labels: enhancement, cleanup

#950 Cleaning up createFreshFeed
  armi/reactor/converters/geometryConverters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/utils/tests/test_codeTiming.py
Labels: enhancement

#951 Removing getMasterCs from getMicroSuffix
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#943 Zones overhaul
  armi/bookkeeping/report/reportInterface.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/meta.py
  armi/operators/settingsValidation.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/grids.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_zones.py
  armi/reactor/zones.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/fwSettings/reportSettings.py
  armi/tests/armiRun.yaml
  armi/tests/detailedAxialExpansion/armiRun.yaml
  armi/tests/refTestCartesian.yaml
  armi/tests/test_user_plugins.py
  armi/tests/zpprTest.yaml
  doc/release/0.2.rst
Labels: enhancement, architecture

#953 Constraining wxPython version
  doc/user/user_install.rst
  setup.py
Labels: bug

#954 Removing getMasterCs from createAssemblyOfType
  armi/reactor/reactors.py
Labels: enhancement
