Repository terrapower/armi, pull requests merged in 2022-02, with the labels that each got.

#553 Added MOVABLE flag to allow for lower plenum to move with control rod…
  armi/reactor/flags.py
Labels: enhancement

#556 Fixing issue where UML diagrams weren't in docs
  doc/release/0.2.rst
  doc/requirements-docs.txt
Labels: bug, documentation

#557 Fixing broken reference link for Inconel Alloy 617
  armi/materials/inconel.py
  doc/user/inputs/index.rst
Labels: documentation, enhancement

#558 Improving Helix constructor to be more correct
  armi/reactor/components/complexShapes.py
  armi/reactor/tests/test_components.py
Labels: enhancement

#565 Adding Graphviz to docs build
  .github/workflows/docs.yaml
Labels: bug, documentation

#530 Addressing NumPy security alert
  armi/meta.py
  doc/release/0.2.rst
  requirements-testing.txt
  requirements.txt
Labels: enhancement

#567 Using git submodule to display tutorial examples in docs
  doc/tutorials/making_your_first_app.rst
  tox.ini
Labels: bug, documentation

#568 Removing unused ThermalHydraulics parameters
  armi/physics/thermalHydraulics/parameters.py
  armi/settings/fwSettings/globalSettings.py
Labels: enhancement

#571 Adding important neutronics settings
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
Labels: enhancement

#577 Fix _swapFluxParam for non-uniform assemblies
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/assemblies.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/grids.py
  armi/reactor/reactors.py
  armi/utils/__init__.py
  armi/utils/mathematics.py
  armi/utils/tests/test_flags.py
  armi/utils/tests/test_mathematics.py
  doc/release/0.2.rst
Labels: bug

#584 Reorganizing Math Utilities
  CONTRIBUTING.md
  armi/apps.py
  armi/bookkeeping/report/reportingUtils.py
  armi/conftest.py
  armi/materials/lithium.py
  armi/materials/sulfur.py
  armi/nucDirectory/nuclideBases.py
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/neutronics/energyGroups.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactors.py
  armi/utils/__init__.py
  armi/utils/mathematics.py
  armi/utils/tests/test_mathematics.py
  armi/utils/tests/test_utils.py
  doc/conf.py
  doc/release/0.2.rst
Labels: architecture, cleanup
