Repository terrapower/armi, pull requests merged in 2023-03, with the labels that each got.

#1202 Fix some sphinx renderings for axialExpansionChanger.py
  armi/reactor/converters/axialExpansionChanger.py
Labels: documentation, cleanup

#1163 Changing the name Material.density3 to density
  armi/materials/air.py
  armi/materials/b4c.py
  armi/materials/caH2.py
  armi/materials/californium.py
  armi/materials/concrete.py
  armi/materials/copper.py
  armi/materials/cs.py
  armi/materials/custom.py
  armi/materials/hafnium.py
  armi/materials/inconel.py
  armi/materials/inconelPE16.py
  armi/materials/lead.py
  armi/materials/leadBismuth.py
  armi/materials/lithium.py
  armi/materials/magnesium.py
  armi/materials/material.py
  armi/materials/molybdenum.py
  armi/materials/nZ.py
  armi/materials/potassium.py
  armi/materials/siC.py
  armi/materials/sodium.py
  armi/materials/sodiumChloride.py
  armi/materials/sulfur.py
  armi/materials/tantalum.py
  armi/materials/tests/test_air.py
  armi/materials/tests/test_b4c.py
  armi/materials/tests/test_be9.py
  armi/materials/tests/test_graphite.py
  armi/materials/tests/test_lithium.py
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_sic.py
  armi/materials/tests/test_sulfur.py
  armi/materials/tests/test_thoriumOxide.py
  armi/materials/tests/test_uZr.py
  armi/materials/tests/test_water.py
  armi/materials/thoriumOxide.py
  armi/materials/uThZr.py
  armi/materials/uraniumOxide.py
  armi/materials/void.py
  armi/materials/water.py
  armi/materials/zincOxide.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/components/component.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  doc/release/0.2.rst
Labels: cleanup, complex

#1164 Using CONF_XXX variables
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/report/newReportUtils.py
  armi/bookkeeping/report/reportInterface.py
  armi/bookkeeping/report/reportingUtils.py
  armi/cases/case.py
  armi/cases/inputModifiers/neutronicsModifiers.py
  armi/cases/inputModifiers/tests/test_inputModifiers.py
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/physics/fuelCycle/__init__.py
  armi/physics/fuelPerformance/settings.py
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/fissionProductModelSettings.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/tests/test_lumpedFissionProduct.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
  armi/physics/neutronics/parameters.py
  armi/physics/neutronics/reports.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/neutronics/tests/test_crossSectionSettings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py
  armi/reactor/converters/parameterSweeps/tests/test_paramSweepConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_reactors.py
  armi/scripts/migration/base.py
  armi/scripts/migration/crossSectionBlueprintsToSettings.py
  armi/settings/tests/test_settings.py
  doc/developer/reports.rst
Labels: cleanup

#1203 Speed up runLog
  armi/runLog.py
Labels: optimization

#1215 Removing potential circular import in reporting
  armi/bookkeeping/report/reportingUtils.py
  armi/physics/fuelCycle/__init__.py
Labels: bug

#1206 Fix tight coupling on lattice interface for Snapshots
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  doc/release/0.2.rst
  doc/user/inputs/settings.rst
Labels: bug, documentation, testing

#1219 Use TempraryDirectoryChanger for Executer.run()
  armi/physics/executers.py
  doc/release/0.2.rst
Labels: enhancement

#1225 Bug fix for precision issue with axial submesh
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  doc/release/0.2.rst
Labels: bug
