Repository terrapower/armi, pull requests merged in 2023-01, with the labels that each got.

#1056 Move output cache runLog level from extra to info
  armi/utils/outputCache.py
Labels: feature request

#1059 Attempting to fix coverage issue by fixing coverage version to 6.5.0
  setup.py
Labels: bug, testing

#1054 Restart docs
  doc/release/0.2.rst
  doc/user/inputs/settings.rst
Labels: documentation

#1063 Moving some axial expansion debug statements to single
  armi/reactor/converters/axialExpansionChanger.py
Labels: cleanup

#1064 Adding description of version metadata setting
  doc/tutorials/walkthrough_inputs.rst
Labels: documentation

#1071 Removing calls to getMasterCs
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cli/reportsEntryPoint.py
  armi/materials/tests/test_materials.py
  armi/nuclearDataIO/cccc/tests/test_nhflux.py
  armi/operators/tests/test_inspectors.py
  armi/physics/neutronics/tests/test_cross_section_manager.py
  armi/reactor/blueprints/tests/test_assemblyBlueprints.py
  armi/reactor/blueprints/tests/test_materialModifications.py
  armi/reactor/converters/parameterSweeps/tests/test_paramSweepConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_reactors.py
  armi/settings/tests/test_settings.py
  armi/tests/test_plugins.py
Labels: architecture, cleanup

#1069 Cleaning out duplicate context import in bootstrap
  armi/_bootstrap.py
Labels: cleanup

#1073 Update pylintrc
  pylintrc
Labels: cleanup

#1067 Fission Product Model with Explicit Fission Products for all Depletable Components
  armi/nuclearDataIO/cccc/isotxs.py
  armi/nuclearDataIO/cccc/tests/test_gamiso.py
  armi/nuclearDataIO/tests/.gitignore
  armi/nuclearDataIO/tests/fixtures/AA.GAMISO
  armi/nuclearDataIO/tests/fixtures/AA.PMATRX
  armi/nuclearDataIO/tests/fixtures/AB.GAMISO
  armi/nuclearDataIO/tests/fixtures/AB.PMATRX
  armi/nuclearDataIO/tests/fixtures/ISOAA
  armi/nuclearDataIO/tests/fixtures/ISOAB
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/xsLibraries.py
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  doc/release/0.2.rst
Labels: bug

#1080 Add new test files to manifest
  MANIFEST.in
Labels: bug

#1081 XS Library Merge Bug
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/xsLibraries.py
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
Labels: bug

#1087 Copy dummy micro XS.
  armi/nuclearDataIO/cccc/isotxs.py
Labels: bug

#1042 Efficiency improvement
  armi/materials/mixture.py
  armi/materials/tests/test_materials.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/parameters.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.2.rst
Labels: optimization

#1091 Fix Sphinx errors in docs for `code-blocks`
  doc/user/inputs/settings.rst
Labels: documentation

#1098 Improve logic for getNumPins
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.2.rst
Labels: bug

#1105 Fixing broken doc link for mpi4py
  doc/developer/parallel_coding.rst
Labels: documentation

#1099 Cleanup umc
  armi/physics/neutronics/parameters.py
  armi/reactor/blocks.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/tests/test_blocks.py
Labels: bug

#1104 Using module-level neutronics settings constants
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/neutronics/tests/test_crossSectionSettings.py
  armi/physics/neutronics/tests/test_cross_section_manager.py
  armi/tests/test_mpiFeatures.py
Labels: cleanup

#1106 Using mockRunLogs in a better way
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/report/tests/test_newReport.py
  armi/bookkeeping/report/tests/test_report.py
  armi/bookkeeping/tests/test_memoryProfiler.py
  armi/cases/tests/test_cases.py
  armi/cli/tests/test_runEntryPoint.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/tests/test_xsNuclides.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_zones.py
  armi/tests/mockRunLogs.py
  armi/tests/test_lwrInputs.py
  armi/tests/test_mpiActions.py
  armi/tests/test_runLog.py
  armi/utils/tests/test_custom_exceptions.py
Labels: cleanup

#1107 Using fuelCycle settings constants
  armi/bookkeeping/report/newReportUtils.py
  armi/bookkeeping/report/reportingUtils.py
  armi/cases/tests/test_cases.py
  armi/operators/operator.py
  armi/physics/fuelCycle/__init__.py
  armi/physics/fuelCycle/assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/fuelHandlerFactory.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/settings.py
  armi/physics/fuelCycle/tests/test_assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/reactors.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/tests/test_settings.py
Labels: cleanup

#1102 Adding a helper method to validate versions in settings files
  armi/operators/settingsValidation.py
  armi/settings/tests/test_settings.py
  doc/tutorials/making_your_first_app.rst
Labels: feature request

#1109 Fixing ruamel.yaml deprecation warning
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/settings/caseSettings.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settings.py
Labels: cleanup

#1033 Add measure of convergence for tight coupling
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/report/newReportUtils.py
  armi/bookkeeping/report/reportingUtils.py
  armi/interfaces.py
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/fwSettings/tests/test_fwSettings.py
  armi/settings/fwSettings/tests/test_tightCouplingSettings.py
  armi/settings/fwSettings/tightCouplingSettings.py
  armi/tests/armiRun.yaml
  armi/tests/detailedAxialExpansion/armiRun.yaml
  armi/tests/test_interfaces.py
  doc/release/0.2.rst
  doc/requirements/srsd.rst
  doc/user/assorted_guide.rst
  doc/user/images/looseCouplingIllustration.png
  doc/user/images/tightCouplingIllustration.png
  doc/user/index.rst
  doc/user/physics_coupling.rst
Labels: feature request

#1113 Expose tight coupling to `OperatorSnapshots`
  armi/operators/operator.py
  armi/operators/snapshots.py
  armi/operators/tests/test_operators.py
  doc/release/0.2.rst
Labels: bug

#1062 Refactoring Material to not subclass Composite
  armi/materials/air.py
  armi/materials/alloy200.py
  armi/materials/b4c.py
  armi/materials/be9.py
  armi/materials/californium.py
  armi/materials/custom.py
  armi/materials/graphite.py
  armi/materials/hastelloyN.py
  armi/materials/ht9.py
  armi/materials/inconel600.py
  armi/materials/inconel625.py
  armi/materials/inconel800.py
  armi/materials/inconelPE16.py
  armi/materials/inconelX750.py
  armi/materials/lead.py
  armi/materials/leadBismuth.py
  armi/materials/lithium.py
  armi/materials/magnesium.py
  armi/materials/material.py
  armi/materials/materialParameters.py
  armi/materials/mgO.py
  armi/materials/mox.py
  armi/materials/potassium.py
  armi/materials/scandiumOxide.py
  armi/materials/siC.py
  armi/materials/sodium.py
  armi/materials/sodiumChloride.py
  armi/materials/tZM.py
  armi/materials/tests/test_air.py
  armi/materials/tests/test_materials.py
  armi/materials/thU.py
  armi/materials/thorium.py
  armi/materials/thoriumOxide.py
  armi/materials/uThZr.py
  armi/materials/uZr.py
  armi/materials/uraniumOxide.py
  armi/materials/void.py
  armi/materials/water.py
  armi/materials/yttriumOxide.py
  armi/materials/zr.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_materialModifications.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/utils/densityTools.py
  armi/utils/tests/test_densityTools.py
  doc/gallery-src/framework/run_materials.py
  doc/release/0.2.rst
  doc/tutorials/materials_demo.ipynb
Labels: architecture, cleanup

#1118 bug fix for xsGroup manager w/ coupling
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/tests/test_cross_section_manager.py
  doc/release/0.2.rst
Labels: bug

#1120 Calculate fission rate density.
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
Labels: enhancement

#1123 Removing prefer-binary PIP requirement
  requirements-testing.txt
  requirements.txt
  tox.ini
Labels: enhancement

#1126 Matching the Magnesium density curve to match the reference
  armi/materials/magnesium.py
  armi/materials/tests/test_materials.py
Labels: bug

#1128 Fixing temperature range of Potassium
  armi/materials/potassium.py
  armi/materials/tests/test_materials.py
  doc/release/0.2.rst
Labels: bug

#1129 Update psuedo density to physical density in materials method
  armi/materials/material.py
  armi/materials/tests/test_materials.py
  doc/release/0.2.rst
Labels: bug

#1131 Correcting concrete density based on reference
  armi/materials/concrete.py
  doc/release/0.2.rst
Labels: bug

#1130 Implement timestep compare argument for database comparison
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/cases/case.py
  armi/cases/suite.py
  armi/cli/compareCases.py
  armi/cli/tests/test_runEntryPoint.py
Labels: enhancement
