Repository terrapower/armi, pull requests merged in 2023-11, with the labels that each got.

#1457 Adding tests to Parameter package
  armi/reactor/composites.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
Labels: documentation, testing

#1461 Making block impl tags unique
  armi/nuclearDataIO/tests/test_xsCollections.py
  armi/reactor/blocks.py
Labels: documentation, cleanup

#1462 Adding impl and test tags for requirements
  armi/interfaces.py
  armi/materials/__init__.py
  armi/materials/material.py
  armi/materials/void.py
  armi/operators/operator.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/plugins.py
Labels: documentation

#1466 Use functools for codeTiming decorator.
  armi/utils/codeTiming.py
  armi/utils/tests/test_utils.py
  doc/release/0.2.rst
Labels: documentation, enhancement

#1463 Adding test and impl tags to assemblies
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
Labels: documentation, testing

#1468 Adding test/impl tags for reactors
  armi/cases/tests/test_cases.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/utils/tests/test_utils.py
Labels: documentation, testing

#1470 Adding Flag/Flags impl and test tags
  armi/reactor/flags.py
  armi/reactor/tests/test_flags.py
  armi/utils/flags.py
  armi/utils/tests/test_flags.py
Labels: documentation, testing

#1474 Removing long value of static member in class of test_composities fro…
  armi/reactor/tests/test_composites.py
Labels: documentation

#1473 Adding even more test crumbs
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/snapshotInterface.py
  armi/bookkeeping/tests/test_snapshot.py
  armi/cases/case.py
  armi/cases/inputModifiers/inputModifiers.py
  armi/cases/suiteBuilder.py
  armi/cases/tests/test_cases.py
  armi/cases/tests/test_suiteBuilder.py
  armi/materials/tests/test_air.py
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_water.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
Labels: documentation, testing

#1476 Adding impl/test crumbs for blueprints
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_assemblyBlueprints.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
Labels: documentation, testing

#1477 Adding impl/test crumbs for reqs
  armi/apps.py
  armi/nuclearDataIO/cccc/compxs.py
  armi/nuclearDataIO/cccc/dif3d.py
  armi/nuclearDataIO/cccc/dlayxs.py
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/geodst.py
  armi/nuclearDataIO/cccc/isotxs.py
  armi/nuclearDataIO/cccc/pmatrx.py
  armi/nuclearDataIO/cccc/tests/test_dif3d.py
  armi/nuclearDataIO/cccc/tests/test_dlayxs.py
  armi/nuclearDataIO/cccc/tests/test_gamiso.py
  armi/nuclearDataIO/cccc/tests/test_geodst.py
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  armi/plugins.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_rz_reactors.py
Labels: documentation, testing

#1482 Adding impl/test crumbs for nucDir
  armi/nucDirectory/elements.py
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/tests/test_elements.py
  armi/nucDirectory/tests/test_nuclideBases.py
Labels: documentation, testing

#1484 Fixing broken req test crumbs
  armi/nucDirectory/tests/test_elements.py
  armi/nucDirectory/tests/test_nuclideBases.py
Labels: documentation, cleanup

#1483 Adding impl/test crumbs from Nala req comments
  armi/cases/suite.py
  armi/cases/tests/test_cases.py
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/isotxs.py
  armi/nuclearDataIO/cccc/pmatrx.py
  armi/nuclearDataIO/cccc/tests/test_pmatrx.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/plugins.py
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/converters/blockConverters.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
Labels: documentation, testing

#1488 Sweeping crumbs for grammatical fixes
  armi/cases/__init__.py
  armi/cases/suite.py
  armi/cases/tests/test_cases.py
  armi/materials/__init__.py
  armi/materials/tests/test_materials.py
  armi/nucDirectory/tests/test_elements.py
  armi/nuclearDataIO/cccc/geodst.py
  armi/operators/operator.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_assemblyBlueprints.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/converters/blockConverters.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/flags.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_flags.py
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_zones.py
  armi/reactor/zones.py
  armi/utils/densityTools.py
  armi/utils/flags.py
  armi/utils/tests/test_densityTools.py
  armi/utils/tests/test_flags.py
  armi/utils/tests/test_hexagon.py
Labels: documentation, cleanup

#1487 Adding requirement crumbs for Materials and Composites
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_uZr.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/grids/grid.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
Labels: documentation, testing

#1489 Moving test class crumbs to unit test crumbs
  armi/cases/suiteBuilder.py
  armi/cases/tests/test_cases.py
  armi/cases/tests/test_suiteBuilder.py
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_water.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/tests/test_reactors.py
  armi/utils/tests/test_hexagon.py
Labels: documentation, testing

#1495 Fixing import loop in test blueprints
  armi/reactor/blueprints/tests/test_gridBlueprints.py
Labels: cleanup

#1493 Adding impl/test crumbs for the Database
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_database3.py
Labels: documentation, testing

#1492 Adding impl/test crumbs for Grid
  armi/materials/tests/test_materials.py
  armi/materials/tests/test_uZr.py
  armi/physics/executers.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/grids/grid.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/structuredgrid.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
Labels: documentation, testing

#1496 Adding crumbs for CLI
  armi/cli/__init__.py
  armi/cli/entryPoint.py
  armi/cli/tests/test_runEntryPoint.py
  armi/cli/tests/test_runSuite.py
Labels: documentation, testing

#1503 Adding tests and crumbs for high-level framework concepts
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/neutronics/tests/test_crossSectionSettings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/reactor/parameters/parameterCollections.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_rz_reactors.py
  armi/settings/tests/test_settings.py
  armi/tests/test_apps.py
  armi/tests/test_interfaces.py
  armi/tests/test_mpiFeatures.py
  armi/tests/test_plugins.py
  armi/tests/test_tests.py
  armi/utils/tests/test_densityTools.py
  armi/utils/tests/test_hexagon.py
Labels: documentation, testing

#1499 Adding crumbs for shuffle logic
  armi/physics/fuelCycle/assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
Labels: documentation, testing

#1505 Adding miscellaneous crumbs
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/tests/test_reactors.py
Labels: documentation, testing

#1500 Adding crumbs for istopic depletion
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/isotopicDepletion/crossSectionTable.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/physics/neutronics/tests/test_crossSectionTable.py
Labels: documentation, testing

#1506 Adding impl/test crumbs
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/layout.py
  armi/materials/mixture.py
  armi/reactor/blocks.py
  armi/reactor/components/__init__.py
  armi/reactor/components/component.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
Labels: documentation, testing

#1507 Adding impl/test crumbs for requirements
  armi/physics/neutronics/energyGroups.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/tests/test_energyGroups.py
  armi/reactor/assemblies.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/grids/structuredgrid.py
Labels: documentation, testing

#1508 Adding some impl crumbs to docstrings
  armi/nuclearDataIO/xsCollections.py
  armi/physics/neutronics/macroXSGenerationInterface.py
  armi/reactor/blocks.py
Labels: documentation, testing
