Repository terrapower/armi, pull requests merged in 2023-06, with the labels that each got.

#1289 Updating phrasing to GitHub PR template.
  .github/pull_request_template.md
Labels: documentation

#1291 Cleaning up TODOs
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/layout.py
  armi/mpiActions.py
  armi/reactor/blocks.py
  armi/reactor/composites.py
  armi/utils/reportPlotting.py
  armi/utils/tests/test_triangle.py
  doc/developer/standards_and_practices.rst
  pylintrc
Labels: documentation

#1292 Building helper tool for when Parameters need to be NumPy arrays
  armi/physics/neutronics/parameters.py
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/reactorParameters.py
Labels: enhancement

#1280 Unifying the Reactor sorting
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/reactor/composites.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
  armi/settings/fwSettings/globalSettings.py
  doc/release/0.2.rst
Labels: enhancement

#1299 Improving HexBlock getWettedPerimeter calculation
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.2.rst
Labels: bug

#1255 Fewer calls to Composite.iterComponents
  armi/reactor/blocks.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/tests/test_components.py
Labels: feature request

#1298 undo setting ndense to 0 for xs gen; move feature to xs gen
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/isotopicOptions.py
  doc/release/0.2.rst
Labels: feature request

#1306 Helping define the PR description field
  .github/pull_request_template.md
Labels: documentation

#1294 Update file names to copy for snapshotRequest
  armi/bookkeeping/snapshotInterface.py
  armi/bookkeeping/tests/test_snapshot.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  doc/release/0.2.rst
Labels: feature request

#1307 Adding unit tests to the LatticePhysicsWriter
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
Labels: testing

#1312 Fixing circular import in GlobalFluxInterface
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
Labels: bug, cleanup

#1288 Change XSGM interface stack position to just before before MC2
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/settings.py
  doc/release/0.2.rst
Labels: feature request

#1308 improve testing coverage for fuelHandlerInterface.interactBOC
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
Labels: testing

#1310 Setting Burnup Peaking Factor to 0.0 when Undefined
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
Labels: feature request

#1309 Add DIF3D Reader to CCCC
  MANIFEST.in
  armi/nuclearDataIO/__init__.py
  armi/nuclearDataIO/cccc/dif3d.py
  armi/nuclearDataIO/cccc/tests/fixtures/simple_hexz.dif3d
  armi/nuclearDataIO/cccc/tests/test_dif3d.py
  armi/physics/neutronics/__init__.py
Labels: feature request

#1316 Correction for axial expansion conservation
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
Labels: feature request

#1319 Version bumping ARMI to 0.2.8
  armi/__init__.py
  armi/apps.py
  armi/bookkeeping/__init__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/report/newReportUtils.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/visualization/entryPoint.py
  armi/cases/suiteBuilder.py
  armi/cli/__init__.py
  armi/context.py
  armi/meta.py
  armi/nucDirectory/nuclideBases.py
  armi/nuclearDataIO/cccc/cccc.py
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/thermalHydraulics/__init__.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/converters/parameterSweeps/__init__.py
  armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/tests/test_reactors.py
  armi/scripts/migration/base.py
  armi/scripts/migration/crossSectionBlueprintsToSettings.py
  armi/settings/caseSettings.py
  armi/utils/tests/test_custom_exceptions.py
  armi/utils/tests/test_plotting.py
  doc/__init__.py
  doc/release/0.2.rst
  ruff.toml
Labels: cleanup

#1324 Applying more ruff rules to the repo
  armi/physics/neutronics/fissionProductModel/fissionProductModel.py
  armi/utils/mathematics.py
  armi/utils/pathTools.py
  ruff.toml
Labels: cleanup

#1327 Adding more ruff simplify rules
  armi/materials/tests/test_air.py
  armi/mpiActions.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/neutronics/reports.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/pinTypeBlockConverters.py
  armi/utils/directoryChangers.py
  armi/utils/pathTools.py
  armi/utils/plotting.py
  ruff.toml
Labels: cleanup

#1332 Finalizing our ruff settings
  .github/workflows/validatemanifest.py
  armi/bookkeeping/snapshotInterface.py
  armi/interfaces.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/nuclearDataIO/cccc/dif3d.py
  armi/nuclearDataIO/cccc/tests/test_dif3d.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/neutronics/isotopicDepletion/crossSectionTable.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/physics/thermalHydraulics/__init__.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/converters/parameterSweeps/__init__.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/utils/flags.py
  armi/utils/mathematics.py
  armi/utils/properties.py
  doc/gallery-src/analysis/run_blockMcnpMaterialCard.py
  doc/gallery-src/framework/run_blockVolumeFractions.py
  doc/gallery-src/framework/run_chartOfNuclides.py
  doc/gallery-src/framework/run_computeReactionRates.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/gallery-src/framework/run_grids1_hex.py
  doc/gallery-src/framework/run_grids2_cartesian.py
  doc/gallery-src/framework/run_grids3_rzt.py
  doc/gallery-src/framework/run_isotxs.py
  doc/gallery-src/framework/run_isotxs2_matrix.py
  doc/gallery-src/framework/run_materials.py
  doc/gallery-src/framework/run_programmaticReactorDefinition.py
  doc/gallery-src/framework/run_reactorFacemap.py
  doc/gallery-src/framework/run_transmutationMatrix.py
  ruff.toml
Labels: cleanup
