Repository terrapower/armi, pull requests merged in 2023-12, with the labels that each got.

#1512 Adding more test crumbs
  armi/nuclearDataIO/cccc/tests/test_isotxs.py
  armi/nuclearDataIO/cccc/tests/test_pmatrx.py
  armi/nuclearDataIO/tests/test_xsCollections.py
  armi/nuclearDataIO/xsCollections.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
Labels: documentation, testing

#1514 Reving unit tests for parallel process param updating
  armi/reactor/composites.py
  armi/reactor/tests/test_parameters.py
Labels: documentation, testing

#1524 Improving grid tests and documentation
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/tests/test_blocks.py
Labels: documentation, testing

#1523 Adding executer options to executer unit test
  armi/physics/tests/test_executers.py
Labels: testing

#1529 Responding to review of assembly requirements
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
Labels: documentation, testing

#1532 Adding new MPI tests to code coverage
  .github/workflows/coverage.yaml
  armi/reactor/tests/test_parameters.py
  armi/tests/test_mpiParameters.py
  tox.ini
Labels: testing

#1517 Updating runLog requirement crumbs
  armi/materials/tests/test_materials.py
  armi/tests/test_runLog.py
Labels: documentation, testing

#1535 Improving XSGM tests
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
Labels: testing

#1520 Updating Framework Concept tests and crumbs
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/tests/test_reactors.py
  armi/tests/test_interfaces.py
  armi/tests/test_plugins.py
Labels: documentation, testing

#1539 Allowing a test to skip if it is being run outside a git repo
  armi/bookkeeping/db/tests/test_database3.py
Labels: testing

#1530 Update docstring of `getAssemblyWithStringLocation`
  armi/reactor/reactors.py
Labels: documentation

#1541 Adding test crumb to settings requirement
  armi/nucDirectory/nucDir.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settingsIO.py
Labels: testing

#1543 Some updates to testing for parameters tests
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
Labels: testing

#1540 Improving tests for composites
  armi/reactor/composites.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
Labels: documentation, testing

#1544 Add a test crumb for a param req
  armi/reactor/tests/test_parameters.py
Labels: testing

#1545 Improving testing and crumbs for blueprints
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
Labels: documentation, testing

#1547 Improving tests and crumbs to Components
  armi/reactor/components/__init__.py
  armi/reactor/components/component.py
  armi/reactor/tests/test_components.py
Labels: documentation, testing

#1549 Fixing issues found in our docstrings
  armi/bookkeeping/db/database3.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  doc/user/physics_coupling.rst
Labels: bug, documentation

#1553 Improving isDepletable test
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
Labels: testing

#1552 Improving Reactor tests and crumbs
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_rz_reactors.py
Labels: documentation, testing

#1554 Fixing broken docstring
  armi/reactor/reactors.py
Labels: documentation

#1555 More converters testing updates
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/converters/tests/test_uniformMesh.py
Labels: testing

#1556 Fixing broken impl tag in geom converters
  armi/reactor/converters/geometryConverters.py
Labels: documentation

#1557 Adding code coverage to FuelHandlers and Core
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/tests/test_reactors.py
Labels: testing

#1559 Add sys info printout for all nodes
  armi/bookkeeping/report/reportingUtils.py
Labels: enhancement

#1560 Create method to retrieve active interfaces
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
Labels: enhancement

#1522 Editorial fixes for various rxcoeff params
  armi/reactor/blockParameters.py
  armi/reactor/reactorParameters.py
Labels: enhancement

#1562 Improving parallel coding documentation
  doc/developer/parallel_coding.rst
  doc/developer/reports.rst
Labels: documentation

#1558 Releasing ARMI v0.3.0!
  doc/release/0.2.rst
  doc/release/0.3.rst
  pyproject.toml
Labels: documentation

#1564 Improving Documentation
  .github/pull_request_template.md
  doc/developer/documenting.rst
  doc/developer/entrypoints.rst
  doc/developer/first_time_contributors.rst
  doc/developer/parallel_coding.rst
  doc/developer/profiling.rst
  doc/developer/reports.rst
  doc/developer/tooling.rst
  doc/release/0.3.rst
  doc/user/accessingEntryPoints.rst
  doc/user/assembly_parameters_report.rst
  doc/user/block_parameters_report.rst
  doc/user/component_parameters_report.rst
  doc/user/core_parameters_report.rst
  doc/user/radial_and_axial_expansion.rst
  doc/user/reactor_parameters_report.rst
  doc/user/user_install.rst
Labels: documentation
