Repository terrapower/armi, pull requests merged in 2023-09, with the labels that each got.

#1395 Allowing users to set powerDensity instead of power
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/conftest.py
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/operators/snapshots.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/reactorParameters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/settings/fwSettings/globalSettings.py
  doc/release/0.2.rst
Labels: enhancement

#1401 Enforcing no-relative-imports via Ruff
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/visualization/vtk.py
  armi/nucDirectory/thermalScattering.py
  armi/nuclearDataIO/__init__.py
  armi/physics/fuelPerformance/executers.py
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/energyGroups.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/safety/__init__.py
  armi/reactor/__init__.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/grids/__init__.py
  armi/reactor/grids/axial.py
  armi/reactor/grids/cartesian.py
  armi/reactor/grids/constants.py
  armi/reactor/grids/grid.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/locations.py
  armi/reactor/grids/structuredgrid.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/grids/thetarz.py
  armi/scripts/migration/__init__.py
  armi/settings/fwSettings/__init__.py
  armi/utils/directoryChangers.py
  ruff.toml
Labels: cleanup

#1369 Don't validate material modifications if they are None
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
Labels: enhancement

#1405 Removing mako from dependencies.
  setup.py
Labels: cleanup

#1406 move setOptionsFromCs to Core.processLoading
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/reactors.py
Labels: cleanup

#1411 Reducing warning spam from zones
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/zones.py
Labels: enhancement

#1404 Replace some cs["string"] with cs[CONF]
  armi/reactor/reactors.py
Labels: cleanup

#1413 Handling the new matplotlib 3.8.0 API changes.
  armi/reactor/converters/blockConverters.py
  armi/utils/plotting.py
Labels: bug

#1409 Switching from setup.py to pyproject.toml
  .github/pull_request_template.md
  .github/workflows/validatemanifest.py
  MANIFEST.in
  README.rst
  armi/meta.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/reactors.py
  armi/runLog.py
  armi/utils/dochelpers.py
  doc/conf.py
  doc/developer/documenting.rst
  doc/developer/first_time_contributors.rst
  doc/developer/tooling.rst
  doc/release/0.2.rst
  doc/requirements-docs.txt
  doc/tutorials/making_your_first_app.rst
  doc/user/user_install.rst
  pyproject.toml
  pytest.ini
  requirements-testing.txt
  requirements.txt
  ruff.toml
  setup.py
  tox.ini
Labels: architecture

#1399 Removed getMasterCs and setMasterCs
  armi/__init__.py
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/cases/suite.py
  armi/cases/tests/test_cases.py
  armi/cli/entryPoint.py
  armi/conftest.py
  armi/interfaces.py
  armi/mpiActions.py
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_reactors.py
  armi/settings/__init__.py
  armi/settings/caseSettings.py
  armi/tests/test_mpiFeatures.py
  doc/gallery-src/framework/run_programmaticReactorDefinition.py
  doc/release/0.2.rst
Labels: architecture

#1410 Enforcing discrete options for neutronics BCs
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
Labels: enhancement

#1416 copy interface inputs to return relative paths
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  armi/operators/settingsValidation.py
  doc/release/0.2.rst
Labels: feature request
