Repository terrapower/armi, pull requests merged in 2023-08, with the labels that each got.

#1368 Cleaning up the CONTRIBUTING.md guide
  CONTRIBUTING.md
  README.rst
  armi/reactor/parameters/parameterDefinitions.py
  doc/developer/first_time_contributors.rst
  doc/developer/index.rst
  doc/developer/standards_and_practices.rst
Labels: documentation, cleanup

#1370 Removing global variable from runLog.py
  armi/runLog.py
  armi/tests/test_runLog.py
Labels: cleanup

#1341 Add Python 3.11 to GH Actions
  .github/workflows/black.yaml
  .github/workflows/unittests.yaml
  .github/workflows/validatemanifest.yaml
  .github/workflows/wintests.yaml
  doc/release/0.2.rst
  doc/requirements-docs.txt
  requirements-testing.txt
  setup.py
Labels: ci

#1381 Reconnect logger after disconnecting in test.
  armi/tests/test_runLog.py
Labels: testing

#1382 Remove coveragepy-lcov dependency during CI.
  .github/workflows/coverage.yaml
  .gitignore
  setup.py
  tox.ini
Labels: documentation

#1371 Adding a little code coverage to the CLIs
  armi/cli/tests/test_runEntryPoint.py
Labels: testing

#1378 Updating documentation dependencies for Python 3.11
  doc/.static/css/theme_fixes.css
  doc/conf.py
  doc/gallery-src/analysis/run_blockMcnpMaterialCard.py
  doc/gallery-src/framework/run_blockVolumeFractions.py
  doc/gallery-src/framework/run_chartOfNuclides.py
  doc/gallery-src/framework/run_computeReactionRates.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/gallery-src/framework/run_grids1_hex.py
  doc/gallery-src/framework/run_grids2_cartesian.py
  doc/gallery-src/framework/run_grids3_rzt.py
  doc/gallery-src/framework/run_isotxs.py
  doc/gallery-src/framework/run_isotxs2_matrix.py
  doc/gallery-src/framework/run_materials.py
  doc/gallery-src/framework/run_programmaticReactorDefinition.py
  doc/gallery-src/framework/run_reactorFacemap.py
  doc/gallery-src/framework/run_transmutationMatrix.py
  doc/requirements-docs.txt
  doc/requirements/srsd.rst
Labels: documentation

#1387 Removing unnecessary f-strings
  armi/cases/case.py
  armi/cli/tests/test_runEntryPoint.py
  armi/interfaces.py
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/transmutations.py
  armi/nuclearDataIO/xsLibraries.py
  armi/physics/fuelPerformance/parameters.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/physics/thermalHydraulics/settings.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/components/__init__.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/uniformMesh.py
  armi/settings/fwSettings/globalSettings.py
Labels: cleanup

#1391 Removing unreachable code block
  armi/reactor/blocks.py
Labels: cleanup

#1390 Fixing broken HTML link in comments
  armi/reactor/parameters/parameterDefinitions.py
Labels: documentation

#1388 Removing global plugin flags
  armi/__init__.py
  armi/apps.py
  armi/reactor/flags.py
  armi/tests/test_apps.py
Labels: enhancement, architecture

#1392 Fixing some miscellaneous TODOs
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/memoryProfiler.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/composites.py
  armi/reactor/grids.py
  armi/reactor/tests/test_grids.py
  armi/settings/fwSettings/globalSettings.py
Labels: cleanup

#1393 Removing unused settings
  armi/settings/fwSettings/globalSettings.py
  armi/tests/test_apps.py
Labels: cleanup

#1358 Ensuring we throw an error on bad YAML files
  armi/nucDirectory/nuclideBases.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/systemLayoutInput.py
  armi/settings/caseSettings.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settingsIO.py
Labels: enhancement

#1383 Move max assembly number out of global scope
  MANIFEST.in
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/tests/armiRun-A0032-aHist-ref.txt
  armi/mpiActions.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/assemblies.py
  armi/reactor/assemblyLists.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactorParameters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_reactors.py
  armi/tests/armiRun-SHUFFLES.txt
  doc/release/0.2.rst
  ruff.toml
Labels: enhancement

#1349 Make SFP a child of reactor.
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/reportInterface.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/tests/1DslabXSByCompTest.yaml
  armi/tests/armiRun-SHUFFLES.txt
  armi/tests/detailedAxialExpansion/refSmallReactor.yaml
  armi/tests/refSmallCartesian.yaml
  armi/tests/refSmallReactor.yaml
  doc/developer/guide.rst
  doc/release/0.2.rst
  doc/user/inputs/blueprints.rst
Labels: enhancement

#1373 Refactor armi.reactor.grids to wider submodule; Grids as ABC
  armi/reactor/grids.py
  armi/reactor/grids/__init__.py
  armi/reactor/grids/axial.py
  armi/reactor/grids/cartesian.py
  armi/reactor/grids/constants.py
  armi/reactor/grids/grid.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/locations.py
  armi/reactor/grids/structuredgrid.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/grids/thetarz.py
Labels: architecture, cleanup

#1394 Fixing gallery example for new working Grids
  doc/gallery-src/framework/run_grids2_cartesian.py
Labels: bug, documentation
