Repository terrapower/armi, pull requests merged in 2023-07, with the labels that each got.

#1334 Adding XS files SHA1 hashes to welcome text
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cli/tests/test_runEntryPoint.py
  armi/physics/neutronics/crossSectionSettings.py
  doc/release/0.2.rst
Labels: enhancement

#1336 Moving Spent Fuel pool off Core and onto Reactor
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/reportInterface.py
  armi/materials/material.py
  armi/materials/tests/test_water.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
  armi/tests/refSmallReactorShuffleLogic.py
  doc/release/0.2.rst
Labels: architecture, cleanup

#1340 Removing the Ring and Pos parameters
  armi/reactor/assemblyParameters.py
Labels: cleanup

#1335 Automating the Material names
  armi/materials/air.py
  armi/materials/alloy200.py
  armi/materials/b4c.py
  armi/materials/be9.py
  armi/materials/caH2.py
  armi/materials/californium.py
  armi/materials/concrete.py
  armi/materials/copper.py
  armi/materials/cs.py
  armi/materials/custom.py
  armi/materials/graphite.py
  armi/materials/hafnium.py
  armi/materials/hastelloyN.py
  armi/materials/ht9.py
  armi/materials/inconel.py
  armi/materials/inconel600.py
  armi/materials/inconel625.py
  armi/materials/inconel800.py
  armi/materials/inconelPE16.py
  armi/materials/inconelX750.py
  armi/materials/lead.py
  armi/materials/leadBismuth.py
  armi/materials/lithium.py
  armi/materials/magnesium.py
  armi/materials/material.py
  armi/materials/mgO.py
  armi/materials/mixture.py
  armi/materials/molybdenum.py
  armi/materials/mox.py
  armi/materials/nZ.py
  armi/materials/potassium.py
  armi/materials/scandiumOxide.py
  armi/materials/siC.py
  armi/materials/sodium.py
  armi/materials/sodiumChloride.py
  armi/materials/sulfur.py
  armi/materials/tZM.py
  armi/materials/tantalum.py
  armi/materials/tests/test_water.py
  armi/materials/thU.py
  armi/materials/thorium.py
  armi/materials/thoriumOxide.py
  armi/materials/uThZr.py
  armi/materials/uZr.py
  armi/materials/uranium.py
  armi/materials/uraniumOxide.py
  armi/materials/void.py
  armi/materials/water.py
  armi/materials/yttriumOxide.py
  armi/materials/zincOxide.py
  armi/materials/zr.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  doc/release/0.2.rst
Labels: enhancement

#1199 Enforce the assignment of a mass fraction to a material to be a float
  armi/materials/material.py
  armi/reactor/tests/test_components.py
  armi/utils/densityTools.py
  doc/release/0.2.rst
Labels: bug, cleanup, feature request

#1343 Removing test_gridGui.py to simplify command line testing
  armi/materials/material.py
  armi/reactor/tests/test_reactors.py
  armi/utils/tests/test_gridGui.py
  doc/conf.py
  tox.ini
Labels: cleanup

#1333 Fix _processIncludes to take StringIO argument
  armi/utils/tests/resources/lower/includeA.yaml
  armi/utils/tests/resources/root.yaml
  armi/utils/tests/test_textProcessors.py
  armi/utils/textProcessors.py
  doc/release/0.2.rst
Labels: bug

#1345 Filling in empty Parameter units and descriptions
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/operators/tests/test_operatorSnapshots.py
  armi/physics/fuelPerformance/parameters.py
  armi/physics/neutronics/parameters.py
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/components/componentParameters.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/composites.py
  armi/reactor/parameters/parameterCollections.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/reactorParameters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
  armi/scripts/__init__.py
  armi/utils/reportPlotting.py
  armi/utils/units.py
  doc/release/0.2.rst
Labels: enhancement

#1351 Removing units.NOT_APPLICABLE in favor of UNITLESS
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
  armi/utils/tests/test_textProcessors.py
  armi/utils/textProcessors.py
  armi/utils/units.py
Labels: cleanup

#1350 Improving ParamLocations of certain TH Parameters
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/parameters/parameterDefinitions.py
Labels: enhancement

#1353 Adding a Component Parameter table to the docs
  doc/user/assembly_parameters_report.rst
  doc/user/block_parameters_report.rst
  doc/user/component_parameters_report.rst
  doc/user/core_parameters_report.rst
  doc/user/index.rst
  doc/user/manual_data_access.rst
  doc/user/reactor_parameters_report.rst
Labels: documentation

#1356 Adding units to Material methods that lack them.
  armi/materials/material.py
Labels: documentation

#1357 Removing unfinished requirements from docs
  doc/index.rst
Labels: documentation
