Repository terrapower/armi, pull requests merged in 2023-10, with the labels that each got.

#1419 Adding ruff check to the GH Actions
  .github/workflows/linting.yaml
  doc/release/0.2.rst
Labels: enhancement

#1429 Version-pinning the h5py library
  pyproject.toml
Labels: bug

#1430 Fixing docs - sphinx needs reqs to be 5 chars min
  doc/conf.py
  doc/requirements/srsd.rst
Labels: documentation

#1422 Allow for different file formats in plotBlockDiagram
  armi/utils/plotting.py
Labels: enhancement

#1431 Removing unused Database3.load() argument
  armi/bookkeeping/db/database3.py
Labels: cleanup

#1426 Add unit test coverage for blocks.py
  armi/reactor/tests/test_blocks.py
Labels: testing

#1434 Removing deprecated Database3.load() param
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
Labels: cleanup

#1438 Removed requiements, so the work can be started fresh
  armi/operators/operator.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/grids/cartesian.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/structuredgrid.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/grids/thetarz.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_reactors.py
  armi/utils/tests/test_utils.py
  doc/release/0.2.rst
  doc/requirements/index.rst
  doc/requirements/sdid.rst
  doc/requirements/srsd.rst
  doc/requirements/str.rst
Labels: documentation, cleanup

#1441 Cleaning up material modification table
  doc/user/inputs/blueprints.rst
Labels: documentation, cleanup

#1433 Cleanup of DB migration scripts
  armi/cli/migrateInputs.py
  armi/migration/__init__.py
  armi/migration/base.py
  armi/migration/m0_1_3.py
  armi/migration/m0_1_6.py
  armi/migration/tests/__init__.py
  armi/migration/tests/test_m0_1_6.py
  armi/migration/tests/test_migration_base.py
  armi/physics/constants.py
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/reactor/blueprints/__init__.py
  armi/scripts/__init__.py
  armi/scripts/migration/crossSectionBlueprintsToSettings.py
  armi/scripts/migration/m0_1_0_newDbFormat.py
Labels: architecture, cleanup

#1439 Misc cleanup
  .github/pull_request_template.md
  armi/bookkeeping/report/tests/test_report.py
  armi/bookkeeping/visualization/utils.py
  armi/materials/__init__.py
  armi/materials/material.py
  armi/materials/tests/test_materials.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/safety/__init__.py
  armi/physics/safety/settings.py
  armi/reactor/tests/test_reactors.py
  armi/utils/tests/test_plotting.py
  doc/developer/tooling.rst
Labels: cleanup

#1445 Let's not run GH Unit Tests on doc-only PRs
  .github/workflows/coverage.yaml
  .github/workflows/unittests.yaml
  .github/workflows/wintests.yaml
Labels: testing, optimization

#1446 Cleaning up bootstrap warning
  armi/_bootstrap.py
Labels: cleanup

#1447 Cleaning out defunct shuffle logic validator
  armi/physics/fuelCycle/settings.py
Labels: cleanup

#1412 Representative block component temperature fix
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  doc/release/0.2.rst
Labels: enhancement

#1454 Test Parameter interaction with DB
  .gitignore
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_parameters.py
Labels: testing

#1455 Cleaning up docstrings and formatting
  armi/apps.py
  armi/bookkeeping/snapshotInterface.py
  armi/cases/suite.py
  armi/cases/suiteBuilder.py
  armi/operators/operator.py
  armi/physics/executers.py
  armi/plugins.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/composites.py
  armi/settings/caseSettings.py
  armi/utils/hexagon.py
  armi/utils/textProcessors.py
  armi/utils/units.py
  doc/developer/parallel_coding.rst
Labels: cleanup
