Repository terrapower/armi, pull requests merged in 2023-02, with the labels that each got.

#1136 Calculate block masses at BOC
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/report/tests/test_report.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/blockParameters.py
  armi/reactor/reactors.py
  doc/release/0.2.rst
Labels: feature request

#1141 Have snapshots disable interfaces based on function as well
  armi/operators/snapshots.py
Labels: feature request

#1140 Updating `TD_frac` for consistency
  armi/materials/material.py
  armi/materials/mox.py
  armi/materials/tests/test_materials.py
  armi/materials/thoriumOxide.py
  armi/materials/uraniumOxide.py
  doc/release/0.2.rst
Labels: enhancement

#1122 Catch invalid material modification keys in the blueprints
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/tests/test_materialModifications.py
Labels: feature request

#1145 Hashing log messages for quicker deduplication
  armi/runLog.py
Labels: cleanup, optimization, low priority

#1149 Pointing the Component.density method at 3D material density
  armi/materials/uraniumOxide.py
  armi/reactor/components/component.py
  armi/reactor/tests/test_components.py
  doc/release/0.2.rst
Labels: bug, cleanup

#1153 Removing unused Life Metal methods from Material
  armi/materials/material.py
Labels: cleanup

#1150 Fixing copper density curve
  armi/materials/copper.py
  armi/materials/tests/test_materials.py
  doc/release/0.2.rst
Labels: bug

#1159 Adding code coverage to snapshots and massFracs
  armi/nuclearDataIO/cccc/tests/test_dlayxs.py
  armi/nuclearDataIO/cccc/tests/test_pmatrx.py
  armi/operators/tests/test_operatorSnapshots.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/tests/test_mpiActions.py
  armi/utils/tests/test_units.py
Labels: testing

#1157 Save HCF assembly parameter to DB
  armi/reactor/assemblyParameters.py
  doc/release/0.2.rst
Labels: bug

#1151 Parse through applyInputParams in the MRO
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/tests/test_materialModifications.py
Labels: bug

#1155 Removing strange ban against super() statements
  doc/developer/standards_and_practices.rst
Labels: documentation

#1169 Bumping version to 0.2.6
  armi/meta.py
  doc/developer/tooling.rst
  doc/release/0.2.rst
Labels: documentation

#1148 Opening up the disable snapshot interfaces list
  armi/operators/snapshots.py
  armi/operators/tests/test_operatorSnapshots.py
Labels: cleanup, feature request

#1170 Removing unused test code
  .gitignore
  README.rst
  armi/materials/tests/test_air.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/tests/test_docs.py
  doc/developer/tooling.rst
Labels: cleanup, testing

#1171 hexHoledCircle
  armi/reactor/components/complexShapes.py
  armi/reactor/components/componentParameters.py
  armi/reactor/tests/test_components.py
Labels: feature request

#1176 Fixed bad Sphinx Needs test link
  armi/reactor/tests/test_components.py
Labels: bug

#1179 Remove unused HCFcoretype setting
  armi/operators/tests/test_inspectors.py
  armi/settings/fwSettings/globalSettings.py
  doc/release/0.2.rst
Labels: cleanup

#1178 Cleanup Interface/Event `runLog.header`
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  doc/release/0.2.rst
Labels: cleanup

#1185 Move imports to method to avoid circular import issue
  armi/reactor/reactors.py
  doc/release/0.2.rst
Labels: bug

#1181 Block Param Data Rotations
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_assemblies.py
Labels: enhancement

#1187 Adding two new badges to the README
  README.rst
Labels: documentation, low priority

#1186 Replace ppt generated illustrations for graphviz
  doc/user/images/looseCouplingIllustration.png
  doc/user/images/tightCouplingIllustration.png
  doc/user/inputs/looseCouplingIllustration.dot
  doc/user/inputs/tightCouplingIllustration.dot
  doc/user/physics_coupling.rst
Labels: documentation

#1183 Fix user plugins case suite
  armi/apps.py
  armi/tests/test_user_plugins.py
Labels: bug

#1172 Edit tight coupling `runLog`s + refactor tight coupling unit tests
  armi/bookkeeping/report/reportingUtils.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
Labels: cleanup

#1201 Update release notes post mortem
  doc/release/0.2.rst
Labels: cleanup
