Repository terrapower/armi, pull requests merged in 2023-05, with the labels that each got.

#1250 Fixing iPython version Bug
  requirements-testing.txt
Labels: bug

#1256 Change b.axialExpTargetComponent to block parameter
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  doc/release/0.2.rst
Labels: bug

#1239 New Option to Control Lattice Physics Update Frequency
  armi/nuclearDataIO/__init__.py
  armi/nuclearDataIO/cccc/tests/test_isotxs.py
  armi/operators/operator.py
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/reactor/blockParameters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_reactors.py
Labels: enhancement

#1241 Fixing UserPlugins.defineFlag
  armi/apps.py
  armi/tests/test_user_plugins.py
Labels: bug

#1213 Update gamma Uniform Mesh Converter
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/blockParameters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  doc/release/0.2.rst
Labels: bug

#1262 Fixing getTemperatureAtDensity to use non-pseduo density
  armi/materials/material.py
  armi/materials/tests/test_materials.py
Labels: bug

#1264 Fixing the Settings Report in the Docs
  armi/physics/neutronics/settings.py
  doc/user/inputs/settings_report.rst
Labels: bug, documentation

#1175 Cleaning up language for our versioning rules
  doc/developer/tooling.rst
Labels: documentation

#1266 Removing Component.getMassDensity
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/components/component.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/tests/test_components.py
Labels: cleanup

#1274 Creating versions setting section
  armi/bookkeeping/db/tests/test_database3.py
  armi/meta.py
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/settingsIO.py
  armi/tests/Godiva.armi.unittest.yaml
  armi/tests/armiRun.yaml
  armi/tests/detailedAxialExpansion/armiRun.yaml
  armi/tests/refTestCartesian.yaml
  armi/tests/tutorials/anl-afci-177.yaml
  armi/tests/tutorials/c5g7-settings.yaml
  doc/release/0.2.rst
  doc/tutorials/walkthrough_inputs.rst
Labels: enhancement

#1276 Releasing v0.2.7
  armi/bookkeeping/db/__init__.py
  armi/materials/tests/test_materials.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/utils/tests/test_mathematics.py
  doc/release/0.2.rst
Labels: documentation

#1281 Pinning the versions of yamlize and ruamel
  setup.py
Labels: bug
