Repository terrapower/armi, pull requests merged in 2024-04, with the labels that each got.

#1665 Conserve mass at component level for a.setBlockMesh()
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
  doc/release/0.3.rst
Labels: enhancement

#1670 Adding a little code coverage to key Assembly methods
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
  doc/release/0.3.rst
Labels: testing

#1668 Mentioning the limitations of YAML files in the docs
  README.rst
  doc/index.rst
  doc/user/inputs.rst
Labels: documentation

#1646 Enforcing a maximum line length of 120
  armi/bookkeeping/report/html.py
  armi/bookkeeping/report/newReports.py
  armi/interfaces.py
  armi/materials/inconel600.py
  armi/materials/inconel625.py
  armi/materials/inconelX750.py
  armi/materials/material.py
  armi/materials/mox.py
  armi/materials/tZM.py
  armi/materials/tests/test_materials.py
  armi/materials/water.py
  armi/nucDirectory/nuclideBases.py
  armi/nuclearDataIO/cccc/cccc.py
  armi/nuclearDataIO/cccc/dlayxs.py
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/pmatrx.py
  armi/nuclearDataIO/cccc/tests/test_dlayxs.py
  armi/nuclearDataIO/xsCollections.py
  armi/operators/tests/test_operators.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/fuelPerformance/settings.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/fissionProductModel/fissionProductModelSettings.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/physics/neutronics/parameters.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/reactorParameters.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/utils/codeTiming.py
  armi/utils/customExceptions.py
  armi/utils/plotting.py
  doc/release/0.3.rst
  pyproject.toml
Labels: documentation, cleanup

#1667 Cleaning out the overly-specific methods in ArmiObject
  armi/physics/neutronics/fissionProductModel/lumpedFissionProduct.py
  armi/physics/neutronics/fissionProductModel/tests/test_lumpedFissionProduct.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/components/__init__.py
  armi/reactor/composites.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_composites.py
  doc/release/0.3.rst
Labels: cleanup

#1686 Improving our detection of Interactive Mode
  armi/context.py
Labels: enhancement

#1692 Moving .coveragerc info into pyproject.toml
  .coveragerc
  .github/workflows/coverage.yaml
  .github/workflows/unittests.yaml
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  doc/release/0.3.rst
  pyproject.toml
Labels: cleanup, ci

#1689 Adding system info logging for Linux
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/context.py
  doc/release/0.3.rst
Labels: feature request

#1671 Removing stub from isotopic depletion init file
  armi/physics/neutronics/isotopicDepletion/__init__.py
  doc/release/0.3.rst
Labels: cleanup

#1691 Fix `safeCopy` to work on Linux
  armi/utils/__init__.py
  armi/utils/tests/test_utils.py
  doc/release/0.3.rst
Labels: bug

#1425 (API Breaking) Finish removal of block.r
  armi/mpiActions.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/blocks.py
  armi/reactor/composites.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_composites.py
  doc/release/0.3.rst
Labels: architecture
