Repository terrapower/armi, pull requests merged in 2024-08, with the labels that each got.

#1806 Don't make a runLog named -mpi.log
  armi/runLog.py
  armi/tests/test_runLog.py
Labels: bug

#1798 Adding some code coverage
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
Labels: testing

#1808 Giving user and group read/write/execute permissions on files created in output cache
  armi/utils/outputCache.py
Labels: enhancement

#1814 Updating setting description to fpModel
  armi/physics/neutronics/fissionProductModel/fissionProductModelSettings.py
Labels: documentation

#1810 Describing the log levels explicitly
  doc/developer/tooling.rst
Labels: documentation

#1815 Adding two-letter XS codes to the input docs
  doc/user/inputs.rst
Labels: documentation

#1821 Reverting chmod change
  armi/utils/outputCache.py
Labels: cleanup

#1809 Fixing deprecation warnings with axial grid method
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/reactor/assemblies.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/grids/__init__.py
  armi/reactor/grids/axial.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
  armi/settings/settingsIO.py
  doc/gallery-src/framework/run_computeReactionRates.py
  doc/release/0.4.rst
Labels: cleanup, testing

#1813 Supporting Python 3.12
  .github/workflows/unittests.yaml
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/cases/tests/test_suiteBuilder.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/reactor/assemblies.py
  doc/release/0.4.rst
  pyproject.toml
Labels: enhancement

#1811 Ingesting tabulate as an internal module
  armi/_bootstrap.py
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/historyTracker.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/reportingUtils.py
  armi/cases/case.py
  armi/cases/suite.py
  armi/cli/checkInputs.py
  armi/mpiActions.py
  armi/nucDirectory/elements.py
  armi/physics/neutronics/__init__.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/composites.py
  armi/reactor/parameters/parameterCollections.py
  armi/reactor/reactors.py
  armi/utils/tabulate.py
  armi/utils/tests/test_tabulate.py
  doc/gallery-src/framework/run_blockVolumeFractions.py
  doc/release/0.4.rst
  doc/user/inputs.rst
Labels: feature request

#1826 Performing assorted cleanup
  .gitignore
  armi/materials/material.py
  armi/reactor/tests/test_reactors.py
  armi/utils/mathematics.py
  armi/utils/reportPlotting.py
  armi/utils/tests/test_mathematics.py
  doc/conf.py
Labels: cleanup

#1825 Fixing bug parsing ReportsEntryPoint CLI
  armi/cli/reportsEntryPoint.py
  armi/cli/tests/test_runEntryPoint.py
  armi/utils/mathematics.py
  doc/release/0.4.rst
Labels: bug

#1830 Adding logging dedupication to ARMI docs
  doc/developer/tooling.rst
Labels: documentation

#1835 Removing defunct flags CORE and REACTOR
  armi/bookkeeping/db/database3.py
  armi/physics/neutronics/tests/test_crossSectionTable.py
  armi/reactor/assemblyLists.py
  armi/reactor/flags.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_assemblies.py
  doc/release/0.4.rst
Labels: cleanup

#1831 Fixing DerivedShape.getArea() for cold=true
  armi/reactor/components/__init__.py
  armi/reactor/tests/test_components.py
  doc/release/0.4.rst
Labels: bug

#1836 Updating coveralls to version 2
  .github/workflows/coverage.yaml
  README.rst
Labels: ci

#1838 Remove the `epsCyclic` setting
  armi/tests/zpprTest.yaml
Labels: cleanup

#1839 Documenting TightCoupling in the GlobalFluxInterface
  doc/user/physics_coupling.rst
Labels: documentation

#1834 Fixing issue displaying defaultdicts in tabulate
  armi/utils/tabulate.py
  armi/utils/tests/test_tabulate.py
Labels: bug

#1842 Adding --skip-inspection to compare-suites
  armi/cases/suite.py
  armi/cli/compareCases.py
  armi/cli/tests/test_runEntryPoint.py
  doc/release/0.4.rst
Labels: feature request
