Repository terrapower/armi, pull requests merged in 2024-05, with the labels that each got.

#1697 Fixing broken path in user docs
  doc/user/inputs.rst
Labels: bug, documentation

#1699 Fix a few notes within User Manual
  doc/user/inputs.rst
  doc/user/manual_data_access.rst
Labels: documentation

#1700 Removing outsideFuelRing parameters
  .github/workflows/find_test_crumbs.py
  armi/reactor/reactorParameters.py
  doc/release/0.3.rst
Labels: cleanup

#1705 Fix safeCopy on Windows
  armi/utils/__init__.py
Labels: bug

#1706 Removing the setting doOrificedTH
  armi/settings/fwSettings/globalSettings.py
  doc/release/0.3.rst
Labels: cleanup

#1707 Reverting earlier change to plotting
  armi/utils/plotting.py
Labels: feature request

#1704 Removing unused parameter rdIterNum
  armi/reactor/reactorParameters.py
  doc/release/0.3.rst
Labels: cleanup

#1708 Fixing the doc publishing build
  .github/workflows/docs.yaml
  .github/workflows/licensechecker.yaml
  .github/workflows/linting.yaml
  .github/workflows/validatemanifest.yaml
Labels: bug, documentation

#1713 Adding the MacOS to CI
  .github/workflows/mac_tests.yaml
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  doc/release/0.3.rst
  doc/user/inputs.rst
Labels: ci

#1716 Fixing units for multigroup gamma flux
  armi/physics/neutronics/parameters.py
Labels: bug, documentation
