Repository terrapower/armi, pull requests merged in 2024-09, with the labels that each got.

#1849 Adding GitHub content protection rule to CI
  .github/workflows/black.yaml
  .github/workflows/coverage.yaml
  .github/workflows/licensechecker.yaml
  .github/workflows/linting.yaml
  .github/workflows/mac_tests.yaml
  .github/workflows/unittests.yaml
  .github/workflows/validatemanifest.yaml
  .github/workflows/wintests.yaml
Labels: ci

#1850 Formatting YAML files
  armi/resources/burn-chain.yaml
  armi/resources/mcc-nuclides.yaml
  armi/tests/1DslabXSByCompTest.yaml
  armi/tests/Godiva-blueprints.yaml
  armi/tests/ThRZSettings.yaml
  armi/tests/ThRZloading.yaml
  armi/tests/armiRun.yaml
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
  armi/tests/refSmallCartesian.yaml
  armi/tests/refSmallReactorBase.yaml
  armi/tests/refSmallSfpGrid.yaml
  armi/tests/refTestCartesian.yaml
  armi/tests/smallestTestReactor/refOneBlockReactor.yaml
  armi/tests/tutorials/anl-afci-177-blueprints.yaml
  armi/tests/tutorials/anl-afci-177.yaml
  armi/tests/tutorials/c5g7-blueprints.yaml
Labels: cleanup

#1847 Stopping deploy Docs and Coverage in forked repos
  .github/workflows/coverage.yaml
  .github/workflows/docs.yaml
Labels: cleanup, ci

#1845 Cleaning out unused code and adding coverage
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/composites.py
  doc/release/0.4.rst
Labels: cleanup

#1856 Adding GH Action to close stale PRs
  .github/workflows/stale.yaml
Labels: ci

#1855 thKernel data type fix
  armi/physics/thermalHydraulics/settings.py
  armi/physics/thermalHydraulics/tests/__init__.py
  armi/physics/thermalHydraulics/tests/test_thermalHydraulicsPlugin.py
  doc/release/0.4.rst
Labels: enhancement

#1858 Allow merging a solute with zero area
  armi/reactor/converters/blockConverters.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.4.rst
Labels: feature request

#1868 Removing unused data files
  armi/resources/config/submitter.cfg
  armi/tests/sfpGeom.yaml
  pyproject.toml
Labels: cleanup

#1865 Documenting dev policy: github issue linking
  armi/bookkeeping/visualization/xdmf.py
  doc/developer/standards_and_practices.rst
Labels: documentation

#1857 Getting syncdbAfterWrite working
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  doc/release/0.4.rst
Labels: bug

#1846 Rotation cleanup: Remove Assembly.rotatePins, make Block.rotatePins private
  armi/physics/fuelCycle/assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/hexAssemblyFuelMgmtUtils.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/utils/hexagon.py
  armi/utils/iterables.py
  armi/utils/tests/test_hexagon.py
  armi/utils/tests/test_iterables.py
  doc/release/0.4.rst
Labels: cleanup

#1872 Ignore code coverage on type checking
  armi/plugins.py
  armi/reactor/__init__.py
  pyproject.toml
Labels: cleanup, ci

#1828 Update fluid volumes after prescribed axial expansion
  armi/reactor/converters/axialExpansionChanger/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  doc/release/0.4.rst
Labels: bug

#1888 Streamlining GitHub CI, to be lighter during development
  .github/workflows/coverage.yaml
  .github/workflows/docs.yaml
  .github/workflows/mac_tests.yaml
  .github/workflows/unittests.yaml
  .github/workflows/wintests.yaml
Labels: enhancement, ci

#1889 Making the xsLibrary tests more thread safe
  armi/nuclearDataIO/tests/test_xsLibraries.py
Labels: cleanup, testing

#1879 Cleanup out defunct to do comments
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/composites.py
  armi/reactor/tests/test_blocks.py
Labels: cleanup

#1881 Renaming Reactor.moveList to Reactor.moves
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/reactor/reactors.py
  doc/release/0.4.rst
Labels: cleanup

#1892 Cleanup image resources
  armi/bookkeeping/report/html.py
  armi/resources/images/armi-icon.ico
  armi/resources/images/armiicon.ico
  doc/.static/TerraPowerLogo.png
  doc/.static/TerraPowerLogo_Large.png
  doc/conf.py
  pyproject.toml
Labels: cleanup

#1852 Write and read material theoretical density to/from database
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/materials/material.py
  armi/materials/tests/test_materials.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/tests/test_materialModifications.py
  armi/reactor/components/component.py
  armi/reactor/components/componentParameters.py
  armi/reactor/parameters/parameterCollections.py
  armi/reactor/tests/test_components.py
  doc/release/0.4.rst
Labels: enhancement

#1895 Start moving settingsValidation to the settings area
  armi/operators/operator.py
  armi/operators/settingsValidation.py
  armi/physics/fuelCycle/settings.py
  armi/physics/fuelPerformance/settings.py
  armi/physics/neutronics/fissionProductModel/fissionProductModelSettings.py
  armi/physics/neutronics/settings.py
  armi/physics/neutronics/tests/test_neutronicsPlugin.py
  armi/settings/settingsValidation.py
  armi/settings/tests/test_inspectors.py
  armi/settings/tests/test_settings.py
  doc/release/0.4.rst
Labels: cleanup

#1905 Fixing typo in new settingsValidation imports
  armi/operators/settingsValidation.py
Labels: bug

#1897 Removing reference to deprecated internal files
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
Labels: cleanup

#1899 Adding ParameterCollection.where for conditional parameter iteration
  armi/reactor/parameters/parameterCollections.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_parameters.py
  doc/release/0.4.rst
Labels: feature request

#1909 Closing the plot in plotConvertedBlock()
  armi/reactor/converters/blockConverters.py
Labels: enhancement

#1910 Fixing misleading comment in FuelHandler.swapCascade()
  armi/physics/fuelCycle/fuelHandlers.py
Labels: cleanup, low priority

#1913 Remove `eqRingSchedule` from test yaml files
  armi/tests/armiRun.yaml
  armi/tests/refTestCartesian.yaml
Labels: cleanup, testing

#1914 Organizing test settings files by category
  armi/tests/ThRZSettings.yaml
  armi/tests/armiRun.yaml
  armi/tests/detailedAxialExpansion/armiRun.yaml
  armi/tests/refTestCartesian.yaml
  armi/tests/smallestTestReactor/armiRunSmallest.yaml
  armi/tests/test_lwrInputs.py
  armi/tests/tutorials/c5g7-settings.yaml
  armi/tests/zpprTest.yaml
Labels: cleanup
