Repository terrapower/armi, pull requests merged in 2024-12, with the labels that each got.

#2019 Improving getOptimalAssemblyOrientation
  armi/physics/fuelCycle/assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/hexAssemblyFuelMgmtUtils.py
  armi/physics/fuelCycle/tests/test_assemblyRotationAlgorithms.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/fuelCycle/tests/test_utils.py
  armi/physics/fuelCycle/utils.py
  doc/release/0.5.rst
Labels: enhancement

#2027 Fixing hex assembly rotation docs
  armi/physics/fuelCycle/hexAssemblyFuelMgmtUtils.py
  doc/user/spatial_block_parameters.rst
Labels: documentation

#2026 Fixing Block docstring
  armi/reactor/blocks.py
Labels: documentation

#2017 account for symmetry in volume integrated parameters in assemblies on symmetry lines
  armi/bookkeeping/tests/test_historyTracker.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/assemblies.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/composites.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/tests/tutorials/data_model.ipynb
Labels: feature request

#2033 Fixing _getParamMax for Volume-Integrated Assembly Params
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
Labels: bug

#2039 First order deps
  pyproject.toml
Labels: documentation, cleanup

#2028 Starting the armi.testing modules
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cli/tests/test_runEntryPoint.py
  armi/context.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
  armi/physics/neutronics/tests/test_crossSectionTable.py
  armi/physics/neutronics/tests/test_macroXSGenerationInterface.py
  armi/reactor/converters/parameterSweeps/tests/test_paramSweepConverters.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/converters/tests/test_meshConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
  armi/testing/__init__.py
  armi/tests/test_plugins.py
  armi/utils/tests/test_utils.py
  doc/release/0.5.rst
Labels: testing, feature request
