Repository terrapower/armi, pull requests merged in 2024-11, with the labels that each got.

#1996 Supporting Python 3.13
  .github/workflows/unittests.yaml
  armi/utils/flags.py
  pyproject.toml
Labels: feature request

#2003 Removing coverage cruft from test CI
  .github/workflows/unittests.yaml
Labels: cleanup, ci

#2004 Improving error testing
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/utils/tests/test_pathTools.py
Labels: cleanup, testing

#1954 Enabling axial expansion with detailed depletion
  armi/physics/neutronics/parameters.py
  armi/reactor/components/componentParameters.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger/axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/tests/test_components.py
  doc/release/0.4.rst
Labels: feature request

#1987 Adding temperature dependence when generating cross sections
  armi/bookkeeping/historyTracker.py
  armi/nuclearDataIO/tests/library-file-generation/mc2v2-dlayxs.inp
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/neutronics/tests/test_crossSectionSettings.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/settings/fwSettings/globalSettings.py
  armi/utils/units.py
  doc/release/0.4.rst
  doc/user/spatial_block_parameters.rst
Labels: feature request

#1982 Use ENDF/B-VII.1 MC2-3 nuclide IDs
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/resources/mcc-nuclides.yaml
  doc/release/0.4.rst
Labels: feature request

#2011 Building docs during PRs
  .github/workflows/docs.yaml
Labels: documentation, ci

#2012 Making output cache detection less specific
  armi/utils/outputCache.py
Labels: enhancement, cleanup

#2009 Releasing ARMI version 0.5.0
  .github/workflows/stale.yaml
  README.rst
  armi/plugins.py
  armi/tests/test_plugins.py
  doc/developer/guide.rst
  doc/release/0.4.rst
  doc/release/0.5.rst
  doc/user/outputs.rst
  pyproject.toml
Labels: documentation, enhancement

#2015 Fixing broken requirement crumbs
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_hexBlockRotate.py
Labels: documentation, cleanup

#1990 Updating pin-related functionality
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/historyTracker.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/physics/fuelCycle/tests/test_assemblyRotationAlgorithms.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/components/component.py
  armi/reactor/components/componentParameters.py
  armi/reactor/composites.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  doc/release/0.5.rst
Labels: feature request

#1999 Cleaning out unnecessary uses of r.o
  armi/mpiActions.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/macroXSGenerationInterface.py
  armi/reactor/assemblies.py
  armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py
  armi/reactor/converters/parameterSweeps/tests/test_paramSweepConverters.py
Labels: cleanup

#2018 Improving calculation for total job memory
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/tests/test_memoryProfiler.py
Labels: cleanup

#2013 Better diagnostics on ISOTXS compare
  armi/nuclearDataIO/cccc/isotxs.py
  armi/nuclearDataIO/xsCollections.py
Labels: feature request

#1989 Adding setting to control MCNP / ENDF library
  armi/physics/neutronics/settings.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  doc/release/0.5.rst
Labels: feature request

#2005 Expose some skip inspection options for `armi.init` and `db.loadOperator`
  armi/__init__.py
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/tests/test_database3.py
  doc/release/0.5.rst
Labels: feature request

#2023 Handling checking for OSs better
  armi/bookkeeping/report/reportingUtils.py
  armi/context.py
  armi/utils/__init__.py
Labels: cleanup

#2022 Move files from temporary directory changer
  armi/bookkeeping/db/database.py
  armi/utils/__init__.py
  armi/utils/directoryChangers.py
  armi/utils/tests/test_utils.py
  doc/release/0.5.rst
Labels: enhancement

#2024 Moving from shutil.copy to safeCopy
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/report/newReports.py
  armi/operators/operator.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/settings/settingsValidation.py
  armi/utils/directoryChangers.py
  armi/utils/outputCache.py
  armi/utils/pathTools.py
  doc/conf.py
Labels: cleanup
