Repository terrapower/armi, pull requests merged in 2024-10, with the labels that each got.

#1912 Alphabetizing Flags.toString results
  armi/reactor/flags.py
  armi/reactor/tests/test_flags.py
  doc/release/0.4.rst
Labels: enhancement

#1919 Mostly parameters related updates to docs
  armi/reactor/parameters/__init__.py
  armi/reactor/parameters/parameterCollections.py
  doc/user/assembly_parameters_report.rst
  doc/user/block_parameters_report.rst
  doc/user/component_parameters_report.rst
  doc/user/core_parameters_report.rst
  doc/user/manual_data_access.rst
  doc/user/reactor_parameters_report.rst
Labels: documentation

#1925 Removing unnecessary column in print-out
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
  doc/release/0.4.rst
Labels: bug

#1859 Use a more robust method for determining number of pins in `HexBlock._rotatePins()`
  armi/reactor/blocks.py
  doc/release/0.4.rst
Labels: feature request

#1929 Fixing edge case in assemblyBlueprint._checkParamConsistency
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/tests/test_materialModifications.py
  doc/release/0.4.rst
Labels: bug

#1891 Adding support for ex-core structures
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/report/reportInterface.py
  armi/cases/case.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/plugins.py
  armi/reactor/__init__.py
  armi/reactor/assemblies.py
  armi/reactor/assemblyLists.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
  armi/reactor/composites.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/excoreStructure.py
  armi/reactor/reactors.py
  armi/reactor/spentFuelPool.py
  armi/reactor/tests/test_excoreStructures.py
  armi/reactor/tests/test_reactors.py
  armi/tests/refSmallReactorShuffleLogic.py
  doc/release/0.4.rst
  doc/user/inputs.rst
Labels: feature request

#1936 Update rotation requirement impl, tag links: Hex specific
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
Labels: documentation

#1933 Ensuring we only calculate smear density for pinned blocks
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#1940 Raising Error when loading inconsistent data from DB
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/tests/test_database3.py
  doc/release/0.4.rst
Labels: feature request

#1928 Removing unusable buildEqRingSchedule
  armi/bookkeeping/db/database3.py
  armi/physics/fuelCycle/hexAssemblyFuelMgmtUtils.py
  armi/physics/fuelCycle/tests/test_hexAssemblyFuelMgmtUtils.py
  armi/tests/test_lwrInputs.py
  armi/tests/tutorials/c5g7-settings.yaml
  doc/release/0.4.rst
Labels: cleanup

#1941 Moving C5G7 into its own test dir
  armi/tests/c5g7/c5g7-blueprints.yaml
  armi/tests/c5g7/c5g7-settings.yaml
  armi/tests/test_lwrInputs.py
  armi/utils/tests/test_plotting.py
  doc/tutorials/walkthrough_lwr_inputs.rst
  pyproject.toml
Labels: cleanup

#1931 Removing defunct comment from getPinCoordinates
  armi/reactor/blocks.py
Labels: documentation

#1948 Removing tabulate as a dependency
  pyproject.toml
Labels: cleanup

#1950 Adding DeprecationWarning for HistoryTrackerInterface
  armi/bookkeeping/historyTracker.py
Labels: documentation

#1951 Removing Assembly.doubleResolution
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
  doc/release/0.4.rst
Labels: cleanup

#1927 Adding Block.getInputHeight
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.4.rst
Labels: feature request

#1935 Adding logic so HexAssemblies are hexagonal
  armi/reactor/assemblies.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_reactors.py
Labels: enhancement

#1952 Removing DoseResultsMapper
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  doc/release/0.4.rst
Labels: cleanup

#1957 Moving anl-afci-177 test files to their own directory
  armi/bookkeeping/tests/_constants.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/cases/tests/test_suiteBuilder.py
  armi/tests/anl-afci-177/anl-afci-177-blueprints.yaml
  armi/tests/anl-afci-177/anl-afci-177-coreMap.yaml
  armi/tests/anl-afci-177/anl-afci-177-fuelManagement.py
  armi/tests/anl-afci-177/anl-afci-177.yaml
  armi/tests/test_notebooks.py
  armi/tests/tutorials/data_model.ipynb
  armi/tests/tutorials/param_sweep.ipynb
  armi/utils/directoryChangers.py
  doc/conf.py
  doc/tutorials/data_model.nblink
  doc/tutorials/making_your_first_app.rst
  doc/tutorials/param_sweep.nblink
  doc/tutorials/walkthrough_inputs.rst
  pyproject.toml
Labels: cleanup

#1959 Reducing warnings while building the docs
  .gitignore
  doc/conf.py
Labels: documentation

#1958 Updating cluster settings
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/report/newReportUtils.py
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/fwSettings/tests/test_fwSettings.py
  armi/settings/tests/test_inspectors.py
  armi/settings/tests/test_settings.py
  armi/settings/tests/test_settingsIO.py
  armi/tests/test_apps.py
  doc/release/0.4.rst
Labels: feature request

#1965 Revert "Updating cluster settings"
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/report/newReportUtils.py
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/fwSettings/tests/test_fwSettings.py
  armi/settings/tests/test_inspectors.py
  armi/settings/tests/test_settings.py
  armi/settings/tests/test_settingsIO.py
  armi/tests/test_apps.py
  doc/release/0.4.rst
Labels: feature request

#1966 Allow users to define flag names with numerical values
  armi/reactor/blocks.py
  armi/reactor/flags.py
  armi/reactor/tests/test_flags.py
  doc/release/0.4.rst
Labels: feature request

#1969 Revert "Revert "Updating cluster settings""
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/report/newReportUtils.py
  armi/cli/modify.py
  armi/cli/tests/test_runEntryPoint.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/fwSettings/tests/test_fwSettings.py
  armi/settings/tests/test_inspectors.py
  armi/settings/tests/test_settings.py
  armi/settings/tests/test_settingsIO.py
  armi/tests/test_apps.py
  doc/release/0.4.rst
Labels: enhancement

#1917 Loading some ARMI DBs without the App that created them
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/passiveDBLoadPlugin.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/reactor/parameters/parameterCollections.py
  armi/reactor/reactorParameters.py
  armi/reactor/tests/test_parameters.py
  armi/tests/test_plugins.py
  doc/release/0.4.rst
Labels: feature request

#1968 Changing default of syncDbAfterWrite to True
  armi/settings/fwSettings/databaseSettings.py
  doc/release/0.4.rst
Labels: feature request

#1961 Renaming Database3 to Database, but preserving the API
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/factory.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/db/tests/test_layout.py
  armi/bookkeeping/mainInterface.py
  armi/bookkeeping/visualization/tests/test_vis.py
  armi/bookkeeping/visualization/vtk.py
  armi/bookkeeping/visualization/xdmf.py
  armi/cli/database.py
  armi/context.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/reactor/tests/test_parameters.py
  armi/tests/tutorials/data_model.ipynb
  doc/user/outputs.rst
Labels: cleanup

#1887 Improving efficiency of reaction rate calcs
  armi/nuclearDataIO/xsCollections.py
  armi/physics/neutronics/globalFlux/__init__.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  doc/release/0.4.rst
Labels: enhancement

#1903 Add some missing nuclides from nuclides.dat
  armi/resources/nuclides.dat
Labels: enhancement

#1972 Fixing CLI syntax warnings at startup
  armi/settings/settingsValidation.py
Labels: cleanup

#1973 Hiding sphinx-needs warnings during doc build
  doc/conf.py
Labels: documentation, cleanup

#1974 Fixing various doc build issues
  armi/bookkeeping/db/database.py
  armi/materials/custom.py
  armi/materials/thU.py
  armi/materials/thorium.py
  armi/materials/thoriumOxide.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/flags.py
  armi/utils/gridEditor.py
  doc/release/0.2.rst
  doc/release/0.4.rst
  doc/user/index.rst
  doc/user/inputs.rst
  doc/user/outputs.rst
  doc/user/radial_and_axial_expansion.rst
  doc/user/user_install.rst
Labels: documentation

#1970 Add new memory runLog info to memoryProfiler.py
  armi/bookkeeping/memoryProfiler.py
  armi/bookkeeping/tests/test_memoryProfiler.py
Labels: enhancement

#1943 HexBlock.rotate updates child spatial locators
  armi/reactor/blocks.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/locations.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_hexBlockRotate.py
  doc/release/0.4.rst
  doc/tutorials/walkthrough_lwr_inputs.rst
  doc/user/index.rst
  doc/user/spatial_block_parameters.rst
Labels: enhancement

#1978 Avoid closing plots that are meant to be interactive.
  armi/nuclearDataIO/xsNuclides.py
  armi/reactor/converters/blockConverters.py
  armi/utils/plotting.py
  doc/gallery-src/analysis/run_hexReactorToRZ.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/gallery-src/framework/run_reactorFacemap.py
Labels: bug, documentation

#1979 Removing a duplicate hex rotation impl tag
  armi/reactor/blocks.py
Labels: documentation

#1981 Fixing HexBlock docstrings
  armi/reactor/blocks.py
  armi/reactor/tests/test_hexBlockRotate.py
Labels: documentation

#1947 Fixing sub-block grids
  armi/_bootstrap.py
  armi/bookkeeping/historyTracker.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/cores.py
  armi/reactor/grids/locations.py
  armi/reactor/grids/structuredGrid.py
  armi/reactor/grids/tests/test_grids.py
  armi/reactor/spentFuelPool.py
  armi/reactor/tests/test_blocks.py
  armi/settings/fwSettings/globalSettings.py
  armi/utils/tests/test_plotting.py
  doc/release/0.4.rst
Labels: bug

#1985 Fixing wetted perimeter for hex inner ducts
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.4.rst
Labels: bug

#1986 Removing defunct import
  armi/utils/pathTools.py
Labels: cleanup

#1926 Fixing HexBlock rotation in plotBlockDiagram
  armi/utils/hexagon.py
  armi/utils/plotting.py
  armi/utils/tests/test_plotting.py
  doc/release/0.4.rst
Labels: bug

#1949 Adding option to create a partially heterogeneous assemblies for 1D XS model
  armi/nuclearDataIO/nuclearFileMetadata.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/xsLibraries.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/physics/neutronics/tests/test_crossSectionSettings.py
  armi/reactor/converters/blockConverters.py
  doc/gallery-src/analysis/run_hexBlockToRZConversion.py
  doc/release/0.4.rst
Labels: enhancement

#1991 Adding unit tests for `CylindricalComponentsDuctHetAverageBlockCollection`
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/converters/tests/test_blockConverter.py
Labels: testing

#1984 Update `copyOrWarn` and `getFileSHA1Hash` to account for directories
  armi/cases/case.py
  armi/utils/__init__.py
  armi/utils/pathTools.py
  armi/utils/tests/test_pathTools.py
  armi/utils/tests/test_utils.py
  doc/release/0.4.rst
Labels: feature request

#1992 Removing SmartList & adding coverage
  .github/workflows/coverage.yaml
  armi/tests/test_interfaces.py
  armi/utils/tests/test_textProcessors.py
  armi/utils/textProcessors.py
  doc/release/0.4.rst
Labels: cleanup, testing
