Repository terrapower/armi, pull requests merged in 2024-01, with the labels that each got.

#1567 Cleanup on Aisle 5! Dirty Testing
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/report/tests/test_report.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/tests/test_reactors.py
  armi/tests/test_lwrInputs.py
  armi/tests/test_notebooks.py
  armi/utils/tests/test_directoryChangers.py
  pyproject.toml
Labels: cleanup, testing

#1565 Remove Parent tests/impls/reqs
  armi/cases/tests/test_cases.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/reactors.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_reactors.py
  armi/tests/test_plugins.py
Labels: documentation

#1569 Cleaning up ARMI Docs
  doc/developer/documenting.rst
  doc/developer/first_time_contributors.rst
  doc/developer/guide.rst
  doc/developer/making_armi_based_apps.rst
  doc/developer/parallel_coding.rst
  doc/developer/reports.rst
  doc/developer/standards_and_practices.rst
  doc/developer/tooling.rst
  doc/release/0.1.rst
  doc/release/0.2.rst
  doc/release/0.3.rst
  doc/release/index.rst
  doc/tutorials/index.rst
  doc/tutorials/making_your_first_app.rst
  doc/tutorials/walkthrough_inputs.rst
  doc/tutorials/walkthrough_lwr_inputs.rst
  doc/user/accessingEntryPoints.rst
  doc/user/assembly_parameters_report.rst
  doc/user/block_parameters_report.rst
  doc/user/component_parameters_report.rst
  doc/user/core_parameters_report.rst
  doc/user/index.rst
  doc/user/inputs.rst
  doc/user/inputs/fuel_management.rst
  doc/user/inputs/index.rst
  doc/user/inputs/settings.rst
  doc/user/inputs/settings_report.rst
  doc/user/looseCouplingIllustration.dot
  doc/user/manual_data_access.rst
  doc/user/outputs.rst
  doc/user/outputs/index.rst
  doc/user/outputs/stdout.rst
  doc/user/physics_coupling.rst
  doc/user/radial_and_axial_expansion.rst
  doc/user/reactor_parameters_report.rst
  doc/user/tightCouplingIllustration.dot
  doc/user/user_install.rst
Labels: documentation, cleanup

#1572 ARMI does not officially support Python 3.6
  doc/user/user_install.rst
Labels: documentation

#1574 Doc fixes for PDF build
  doc/developer/guide.rst
  doc/developer/profiling.rst
  doc/tutorials/walkthrough_lwr_inputs.rst
  doc/user/inputs.rst
  doc/user/physics_coupling.rst
  doc/user/radial_and_axial_expansion.rst
Labels: documentation

#1575 Adding longtable class to a table in docs
  doc/user/outputs.rst
Labels: documentation

#1576 Adding list-table powers to the docs
  armi/utils/dochelpers.py
  armi/utils/tests/test_dochelpers.py
  doc/user/inputs.rst
Labels: documentation

#1578 Cleaning up documentation
  armi/utils/dochelpers.py
  doc/.static/looseCouplingIllustration.dot
  doc/.static/tightCouplingIllustration.dot
  doc/developer/making_armi_based_apps.rst
  doc/user/physics_coupling.rst
Labels: documentation

#1580 Cleaning up the docs... again
  armi/materials/tests/test_materials.py
  doc/developer/parallel_coding.rst
Labels: documentation, cleanup, testing

#1582 Adding test crumb finder to CI
  .github/workflows/find_test_crumbs.py
  .github/workflows/wintests.yaml
Labels: testing

#1581 Adding interactCoupled to dev docs
  README.rst
  armi/__init__.py
  armi/bookkeeping/db/tests/__init__.py
  doc/developer/guide.rst
Labels: documentation

#1586 Removing reference to CaseSettings class.
  armi/bookkeeping/db/database3.py
  armi/cases/case.py
  armi/cases/inputModifiers/inputModifiers.py
  armi/cases/suite.py
  armi/cases/suiteBuilder.py
  armi/cli/modify.py
  armi/interfaces.py
  armi/operators/operator.py
  armi/physics/executers.py
  armi/plugins.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactors.py
  armi/reactor/systemLayoutInput.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settings.py
  armi/tests/tutorials/data_model.ipynb
  doc/developer/guide.rst
  doc/release/0.2.rst
Labels: documentation, cleanup

#1584 Adding implementation description to runLog impl crumbs
  armi/runLog.py
Labels: documentation

#1587 Adding implementation information to the materials package
  armi/materials/__init__.py
  armi/materials/material.py
  armi/materials/void.py
Labels: documentation

#1588 Adding implementation details to tags in globalFlux
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
Labels: documentation

#1593 Add implementation descriptions for energyGroups and macroXSGenerationInterface
  armi/physics/neutronics/energyGroups.py
  armi/physics/neutronics/macroXSGenerationInterface.py
Labels: documentation

#1585 Adding more implementation detail to our docstrings
  armi/__init__.py
  armi/apps.py
  armi/interfaces.py
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  armi/operators/settingsValidation.py
  armi/plugins.py
  armi/settings/caseSettings.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/setting.py
Labels: documentation

#1603 Adding implementation text to neutronics settings
  armi/physics/neutronics/settings.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/reactor/converters/uniformMesh.py
Labels: documentation

#1602 Adding implementation text for Grids
  armi/reactor/grids/grid.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/grids/locations.py
  armi/reactor/grids/structuredgrid.py
  armi/reactor/grids/tests/test_grids.py
Labels: documentation

#1596 Adding description to impl tags in `cases`
  armi/cases/case.py
  armi/cases/inputModifiers/inputModifiers.py
  armi/cases/suite.py
  armi/cases/suiteBuilder.py
Labels: documentation

#1609 Adding CLI implementation text
  armi/cli/__init__.py
  armi/cli/entryPoint.py
Labels: documentation

#1610 Adding implementation text for Utils module
  armi/utils/densityTools.py
  armi/utils/flags.py
  armi/utils/hexagon.py
Labels: documentation

#1604 Update iml tags for assemblies.py
  armi/reactor/assemblies.py
Labels: documentation

#1598 Adding impl tag descriptions to ``parameters``
  armi/reactor/parameters/parameterDefinitions.py
Labels: documentation

#1612 Adding implementation details to tags in the xsgm
  armi/physics/neutronics/crossSectionGroupManager.py
Labels: documentation

#1601 Add implementation text for zones.py
  armi/reactor/zones.py
Labels: documentation

#1615 Improving implementation text for axial expansion
  armi/reactor/blocks.py
  armi/reactor/converters/axialExpansionChanger.py
Labels: documentation

#1595 Add longer descriptions to impls in `flags`
  armi/reactor/flags.py
Labels: documentation

#1597 Add implementation text for reactors.py.
  armi/reactor/reactors.py
Labels: documentation

#1600 Adding impl tag descriptions to ``components``
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/tests/test_components.py
Labels: documentation

#1599 Adding impl tag descriptions to ``composites``
  armi/reactor/composites.py
Labels: documentation

#1589 Add longer descriptions for `fuelCycle` impls
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
Labels: documentation

#1606 Add longer descriptions to `blueprints` impls
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/reactorBlueprint.py
Labels: documentation

#1616 Adding implementation text for BlockConverters
  armi/reactor/converters/blockConverters.py
Labels: documentation

#1611 Adding implementation text to bookkeeping
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/historyTracker.py
  armi/bookkeeping/snapshotInterface.py
Labels: documentation

#1594 Add longer descriptions for `executers` impls
  armi/physics/executers.py
Labels: documentation

#1618 Add impl tag descriptions for uniformMesh.py
  armi/reactor/converters/uniformMesh.py
Labels: documentation

#1614 Fix getNeighboringCellIndices
  armi/reactor/grids/structuredgrid.py
  armi/reactor/tests/test_reactors.py
  doc/release/0.3.rst
Labels: bug

#1613 FluxFiles Deserve Hashes Too!
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
Labels: enhancement

#1605 Details for `nuclearDataIO` impl tags
  armi/nuclearDataIO/cccc/cccc.py
  armi/nuclearDataIO/cccc/dif3d.py
  armi/nuclearDataIO/cccc/dlayxs.py
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/geodst.py
  armi/nuclearDataIO/cccc/isotxs.py
  armi/nuclearDataIO/cccc/pmatrx.py
  armi/nuclearDataIO/xsCollections.py
Labels: documentation

#1619 Add descriptions for impls in the `blocks` module
  armi/reactor/blocks.py
Labels: documentation

#1617 Removing the non-Python term class method
  armi/plugins.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/composites.py
  armi/reactor/parameters/__init__.py
  armi/reactor/parameters/parameterDefinitions.py
  armi/settings/setting.py
Labels: documentation, cleanup, low priority

#1625 Hiding attribute values that are not useful
  armi/nucDirectory/nuclideBases.py
  armi/physics/constants.py
  armi/physics/neutronics/energyGroups.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
Labels: documentation

#1626 Cleaning up various docstring errors
  armi/cases/suite.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/reactor/assemblies.py
  armi/settings/settingsIO.py
Labels: documentation, cleanup

#1627 Fix a couple of RST formatting issues
  armi/nuclearDataIO/cccc/cccc.py
  armi/reactor/blocks.py
Labels: documentation

#1629 Improving docs: settings report and missing impl text
  armi/reactor/components/__init__.py
  doc/user/inputs.rst
Labels: documentation

#1631 Remove empty sections from docs
  doc/user/radial_and_axial_expansion.rst
Labels: documentation, cleanup

#1632 Fixing release notes for 0.3.0
  doc/release/0.3.rst
Labels: documentation

#1634 Catchall PR for minor formatting/typo updates to docstrings
  armi/materials/thU.py
  armi/materials/thorium.py
  armi/materials/thoriumOxide.py
  armi/nucDirectory/elements.py
  armi/nuclearDataIO/cccc/cccc.py
  armi/nuclearDataIO/xsCollections.py
  armi/reactor/blocks.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/converters/blockConverters.py
  armi/reactor/reactors.py
  doc/user/inputs.rst
Labels: documentation

#1638 Fixing docstring example formatting
  armi/apps.py
  armi/interfaces.py
  armi/nuclearDataIO/cccc/compxs.py
  armi/nuclearDataIO/cccc/nhflux.py
  armi/nuclearDataIO/xsCollections.py
  armi/nuclearDataIO/xsNuclides.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/reactors.py
  armi/reactor/zones.py
  armi/settings/fwSettings/tightCouplingSettings.py
  armi/utils/mathematics.py
Labels: documentation

#1642 Improving the formatting of some broken See Also's
  armi/nuclearDataIO/cccc/nhflux.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger.py
Labels: documentation

#1643 Fix pural/singular grammar issue
  armi/reactor/assemblies.py
Labels: documentation
