Repository terrapower/armi, pull requests merged in 2024-06, with the labels that each got.

#1719 Fixing docs build on MacOS, and fixing docs docs
  .gitignore
  doc/developer/documenting.rst
  pyproject.toml
Labels: documentation

#1720 Removing wxpython from the docs build
  pyproject.toml
Labels: documentation

#1717 Replacing the concrete material with a better reference
  armi/materials/concrete.py
  doc/release/0.3.rst
Labels: documentation

#1653 Inherit XS Settings when creating a new XS ID
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  doc/release/0.3.rst
Labels: bug

#1659 Changing constant params to Volume Integrated
  armi/reactor/blockParameters.py
  doc/release/0.3.rst
Labels: enhancement

#1451 Remove deprecated core param, fixing optional history.
  armi/utils/reportPlotting.py
Labels: cleanup

#1729 Clearing worker processor instances of reactor state after every interaction
  armi/bookkeeping/memoryProfiler.py
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  armi/tests/test_mpiFeatures.py
Labels: optimization

#1725 Make `peakPercentBu` a `cumulative` and `eq cumulative shift` param
  armi/reactor/blockParameters.py
Labels: enhancement

#1730 Fixing issue with _finalizeInteract in serial jobs
  armi/operators/operatorMPI.py
Labels: bug

#1731 Add more prominent grid editor docs with image.
  .gitignore
  armi/utils/gridEditor.py
  doc/.static/gridEditor.png
  doc/user/inputs.rst
Labels: documentation

#1732 Adding code coverage to FH & GlobalFluxInt
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
Labels: testing

#1735 Adding code coverage
  armi/bookkeeping/report/__init__.py
  armi/bookkeeping/report/data.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cli/tests/test_runEntryPoint.py
Labels: testing

#1733 Adding descriptions to two settings
  armi/bookkeeping/mainInterface.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/setting.py
Labels: documentation

#1743 We shouldn't be wiping the global elements durint tests
  armi/nucDirectory/tests/test_elements.py
  armi/nucDirectory/tests/test_nucDirectory.py
  armi/nucDirectory/tests/test_nuclideBases.py
Labels: cleanup, testing

#1744 Making MacOS unit tests parallel on GH Actions
  .github/workflows/mac_tests.yaml
  .github/workflows/unittests_old.yaml
  armi/runLog.py
  doc/user/user_install.rst
  pyproject.toml
Labels: testing, optimization, low priority, ci

#1737 Creating a one-block test reactor to speed up testing
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/report/tests/test_newReport.py
  armi/bookkeeping/report/tests/test_report.py
  armi/bookkeeping/tests/test_memoryProfiler.py
  armi/bookkeeping/visualization/tests/test_vis.py
  armi/cases/tests/test_cases.py
  armi/cli/tests/test_runEntryPoint.py
  armi/operators/tests/test_operatorSnapshots.py
  armi/operators/tests/test_operators.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/neutronics/tests/test_crossSectionTable.py
  armi/physics/neutronics/tests/test_macroXSGenerationInterface.py
  armi/reactor/converters/parameterSweeps/tests/test_paramSweepConverters.py
  armi/tests/refSmallReactorShuffleLogic.py
  armi/tests/smallestTestReactor/armiRunSmallest.yaml
  armi/tests/smallestTestReactor/refOneBlockReactor.yaml
  armi/tests/smallestTestReactor/refSmallestReactor.yaml
  armi/tests/test_mpiActions.py
  armi/tests/test_mpiFeatures.py
  armi/tests/test_plugins.py
  armi/tests/test_user_plugins.py
  armi/utils/tests/test_plotting.py
  armi/utils/tests/test_reportPlotting.py
  armi/utils/tests/test_utils.py
  doc/release/0.3.rst
  pyproject.toml
Labels: testing, optimization

#1750 Deleting objects that are still trying to hold on to old reactor after reset
  armi/operators/operator.py
  armi/operators/operatorMPI.py
  doc/release/0.3.rst
Labels: optimization

#1751 Clean up a minor bug in #1653
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  doc/release/0.3.rst
Labels: bug

#1752 Cleaning up docstring and unused instance variable
  armi/reactor/assemblies.py
Labels: cleanup

#1745 Custom densities
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  armi/tests/test_lwrInputs.py
  armi/tests/tutorials/c5g7-blueprints.yaml
  doc/release/0.3.rst
  doc/user/inputs.rst
Labels: feature request

#1756 Fix NEA document links in tutorial
  armi/tests/tutorials/c5g7-blueprints.yaml
  doc/tutorials/walkthrough_lwr_inputs.rst
Labels: documentation
