Repository terrapower/armi, pull requests merged in 2024-07, with the labels that each got.

#1759 Moving where we create log dirs
  armi/runLog.py
Labels: enhancement

#1760 Removing custom density from refSmallReactorBase
  armi/tests/refSmallReactorBase.yaml
Labels: enhancement

#1761 Adding descriptions to fuel cycle settings
  armi/physics/fuelCycle/settings.py
  armi/settings/fwSettings/globalSettings.py
Labels: documentation

#1758 Removing unused setting
  armi/settings/fwSettings/globalSettings.py
Labels: cleanup

#1764 Filling in descriptions on settings
  armi/settings/fwSettings/databaseSettings.py
  armi/settings/tests/test_settingsIO.py
Labels: documentation

#1766 Add timestep keyword to interface headers in stdout
  armi/cases/tests/test_cases.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  doc/release/0.3.rst
Labels: feature request

#1769 Reducing the number of warnings when building docs
  armi/bookkeeping/tests/test_historyTracker.py
  armi/materials/__init__.py
  armi/materials/material.py
  armi/nucDirectory/elements.py
  armi/nuclearDataIO/cccc/__init__.py
  armi/nuclearDataIO/cccc/gamiso.py
  armi/nuclearDataIO/cccc/pmatrx.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/plugins.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/grids/axial.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/reactors.py
  doc/.static/dochelpers.py
  doc/developer/tooling.rst
  doc/user/inputs.rst
Labels: documentation, cleanup

#1726 Isolating jagged arrays for numpy compatibility
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/jaggedArray.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_jaggedArray.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/physics/neutronics/__init__.py
  armi/reactor/composites.py
  armi/utils/properties.py
  doc/release/0.3.rst
  doc/user/outputs.rst
  pyproject.toml
Labels: enhancement

#1778 Make new jaggedArray backwards compatible
  armi/bookkeeping/db/jaggedArray.py
  armi/bookkeeping/db/tests/test_jaggedArray.py
Labels: enhancement

#1777 Fixing two semi-broken unit tests
  armi/cli/tests/test_runEntryPoint.py
  armi/context.py
  armi/utils/pathTools.py
Labels: bug

#1090 Write last time node of each cycle rather than EOC to database
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/mainInterface.py
  armi/operators/operator.py
  doc/release/0.3.rst
Labels: feature request

#1783 Fix snapshot
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
  armi/operators/operator.py
  armi/operators/snapshots.py
  armi/operators/tests/test_operatorSnapshots.py
Labels: bug

#1770 Updating the ruff linter to 0.5.1
  .github/workflows/linting.yaml
  armi/_bootstrap.py
  armi/bookkeeping/db/database3.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/historyTracker.py
  armi/bookkeeping/tests/__init__.py
  armi/bookkeeping/visualization/__init__.py
  armi/cases/__init__.py
  armi/cases/case.py
  armi/cases/suite.py
  armi/cli/entryPoint.py
  armi/context.py
  armi/interfaces.py
  armi/nuclearDataIO/cccc/__init__.py
  armi/nuclearDataIO/cccc/cccc.py
  armi/nuclearDataIO/cccc/compxs.py
  armi/nuclearDataIO/cccc/isotxs.py
  armi/nuclearDataIO/cccc/pmatrx.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/xsCollections.py
  armi/operators/settingsValidation.py
  armi/operators/tests/test_operators.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/fuelPerformance/__init__.py
  armi/physics/neutronics/crossSectionSettings.py
  armi/physics/thermalHydraulics/__init__.py
  armi/reactor/assemblyLists.py
  armi/reactor/assemblyParameters.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/components/__init__.py
  armi/reactor/components/component.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/grids/hexagonal.py
  armi/reactor/tests/test_assemblies.py
  armi/settings/__init__.py
  armi/utils/__init__.py
  armi/utils/flags.py
  armi/utils/mathematics.py
  armi/utils/parsing.py
  armi/utils/pathTools.py
  armi/utils/plotting.py
  armi/utils/textProcessors.py
  doc/conf.py
  doc/developer/standards_and_practices.rst
  doc/release/0.3.rst
  pyproject.toml
Labels: low priority

#1786 Fix interactive versus batch mode check
  armi/context.py
  doc/release/0.3.rst
Labels: bug

#1773 Removing the unused method Case.buildCommand
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  doc/release/0.3.rst
Labels: cleanup

#1774 Forcing Parameters and Settings to have Descriptions
  armi/reactor/parameters/parameterDefinitions.py
  armi/settings/caseSettings.py
  armi/settings/setting.py
  armi/settings/tests/test_settings.py
Labels: enhancement

#1787 Minor docstring fix in database3
  armi/bookkeeping/db/database3.py
Labels: documentation, cleanup

#1790 Add virt memory attribute to memory profiler
  armi/bookkeeping/memoryProfiler.py
Labels: feature request

#1791 Adding a couple little unit tests for context.py
  armi/context.py
  armi/tests/test_context.py
  armi/tests/test_mpiFeatures.py
Labels: testing, low priority

#1795 Testing recent database changes
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/operators/tests/test_operators.py
Labels: testing

#1788 Fix MultipleComponentMerger with DerivedShape solvent
  armi/reactor/converters/blockConverters.py
  armi/reactor/converters/tests/test_blockConverter.py
Labels: bug

#1796 Adding year to time logging
  armi/cases/tests/test_cases.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  doc/release/0.3.rst
Labels: feature request

#1800 Releasing ARMI 0.4.0
  .github/workflows/wintests.yaml
  doc/release/0.3.rst
  doc/release/0.4.rst
  pyproject.toml
Labels: enhancement

#1801 Fixing typos in the docs
  doc/developer/documenting.rst
  doc/developer/tooling.rst
Labels: documentation, cleanup

#1803 Fixing misplaced impl tags
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
Labels: documentation
