Repository terrapower/armi, pull requests merged in 2025-08, with the labels that each got.

#2199 Add 3 nuclides to `getDefaultNuclideFlags`
  armi/reactor/blueprints/isotopicOptions.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
Labels: testing, feature request

#2210 Removing python-dateutil dependency
  armi/utils/parsing.py
  pyproject.toml
Labels: cleanup

#2214 Fixing error in recent doc change
  doc/.static/automateScr.py
Labels: bug, documentation

#2228 Fixing bug in Air.pseudoDensity when given Celsius T
  armi/materials/air.py
  armi/materials/tests/test_air.py
Labels: bug

#2226 Fix equality of MultiIndexLocator and CoordinateLocation
  armi/reactor/grids/locations.py
  armi/reactor/grids/tests/test_grids.py
Labels: bug

#2232 Handling BOL times better
  armi/operators/operator.py
Labels: enhancement

#2236 Handle pinIndices for blocks that don't have fuel
  armi/reactor/blocks.py
  armi/reactor/components/component.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#2218 Adding a method to get cycle/node combinations for a time interval
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/tests/test_database3.py
Labels: feature request

#2230 Adding Composite.getFirstComponent method
  armi/reactor/composites.py
  armi/reactor/tests/test_composites.py
Labels: enhancement

#2238 Trying to speed up docs build
  .github/workflows/coverage.yaml
  .github/workflows/docs.yaml
  .github/workflows/licensechecker.yaml
  .github/workflows/linting.yaml
  .github/workflows/unittests.yaml
  .github/workflows/validatemanifest.yaml
Labels: documentation

#2240 Cleaning trace and profile out of RunEntryPoint
  armi/cli/run.py
Labels: cleanup

#2245 Fixing invalid any() signature
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
Labels: bug

#2246 Bumping ARMI to 0.6.0
  pyproject.toml
Labels: documentation

#2235 Adding two geometry parameters
  armi/reactor/assemblyParameters.py
  armi/reactor/blueprints/tests/test_blueprints.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/componentParameters.py
  armi/reactor/components/tests/test_complexShapes.py
Labels: feature request

#2248 Fixing issue loading from snapshots database
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
Labels: bug

#2257 Improving Code Coverage for Blocks and MPIAction
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
  armi/tests/test_mpiActions.py
Labels: testing
