Repository terrapower/armi, pull requests merged in 2025-04, with the labels that each got.

#2106 Add Core.iterBlocks and Assembly.iterBlocks
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/visualization/tests/test_vis.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/fissionProductModel/tests/test_lumpedFissionProduct.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
  armi/physics/neutronics/tests/test_macroXSGenerationInterface.py
  armi/reactor/assemblies.py
  armi/reactor/converters/axialExpansionChanger/axialExpansionChanger.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/meshConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/reactor/cores.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_cores.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_rz_reactors.py
  armi/utils/reportPlotting.py
  armi/utils/tests/test_plotting.py
Labels: enhancement

#2107 Handing empty string defaults better in copyInterfaceInputs
  armi/cases/case.py
  armi/cases/tests/test_cases.py
Labels: feature request

#2102 Fixing issue in copyInterfaceInputs with one file
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  armi/interfaces.py
Labels: bug

#2110 Combining three .gitignore files into one
  .gitignore
  armi/nuclearDataIO/tests/.gitignore
  armi/tests/tutorials/.gitignore
Labels: cleanup

#2111 fix side effects from tests
  armi/bookkeeping/db/tests/test_passiveDBLoadPlugin.py
  armi/settings/tests/test_settings.py
Labels: testing

#2114 Allowing component area to be queried at arbitrary temp
  armi/reactor/components/__init__.py
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/components/tests/__init__.py
  armi/reactor/components/tests/test_basicShapes.py
  armi/reactor/components/tests/test_complexShapes.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/tests/test_components.py
Labels: enhancement, cleanup

#2105 Removing support for XML geom files
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/factory.py
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/bookkeeping/mainInterface.py
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/tests/test_historyTracker.py
  armi/cases/case.py
  armi/cases/inputModifiers/inputModifiers.py
  armi/cases/inputModifiers/neutronicsModifiers.py
  armi/cases/inputModifiers/pinTypeInputModifiers.py
  armi/cases/inputModifiers/tests/test_inputModifiers.py
  armi/cases/inputModifiers/tests/test_pinTypeInputModifiers.py
  armi/cases/suiteBuilder.py
  armi/cases/tests/test_cases.py
  armi/cases/tests/test_suiteBuilder.py
  armi/cli/database.py
  armi/operators/operator.py
  armi/operators/tests/test_operators.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
  armi/reactor/grids/thetarz.py
  armi/reactor/reactors.py
  armi/reactor/systemLayoutInput.py
  armi/reactor/tests/test_geometry.py
  armi/reactor/tests/test_rz_reactors.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/settingsValidation.py
  armi/tests/1DslabXSByCompTest.yaml
  armi/tests/ThRZGeom.xml
  armi/tests/ThRZSettings.yaml
  armi/tests/ThRZloading.yaml
  armi/tests/geom.xml
  armi/tests/geom1Assem.xml
  armi/tests/trz_geom.xml
  armi/tests/tutorials/param_sweep.ipynb
  armi/tests/zpprTest.yaml
  armi/tests/zpprTestGeom.xml
  armi/tests/zpprTestGeom.yaml
  armi/utils/gridEditor.py
  armi/utils/tests/test_tabulate.py
  armi/utils/tests/test_textProcessors.py
  armi/utils/textProcessors.py
  doc/user/outputs.rst
  pyproject.toml
Labels: architecture, cleanup

#2100 Adding more info to STR intro
  doc/qa_docs/str.rst
Labels: documentation

#2127 Removing 3 unused Settings
  armi/physics/fuelCycle/settings.py
  armi/physics/neutronics/settings.py
  armi/settings/fwSettings/databaseSettings.py
  armi/settings/fwSettings/globalSettings.py
  armi/settings/fwSettings/tests/test_fwSettings.py
Labels: cleanup

#2128 Created a fast flux energy structure for calculating fast flux
  armi/physics/neutronics/energyGroups.py
Labels: feature request

#2123 Removing permanently skipped tests
  armi/nuclearDataIO/cccc/tests/test_dlayxs.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
Labels: cleanup, testing

#2126 Removing old TODO comments from the codebase
  armi/__main__.py
  armi/bookkeeping/db/database.py
  armi/bookkeeping/memoryProfiler.py
  armi/interfaces.py
  armi/mpiActions.py
  armi/nuclearDataIO/xsCollections.py
  armi/operators/operator.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/macroXSGenerationInterface.py
  armi/physics/neutronics/settings.py
  armi/reactor/blocks.py
  armi/reactor/blueprints/__init__.py
  armi/reactor/blueprints/assemblyBlueprint.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/composites.py
  armi/reactor/cores.py
  armi/reactor/grids/locations.py
  armi/settings/caseSettings.py
  armi/settings/settingsIO.py
  armi/settings/tests/test_settingsIO.py
  armi/utils/asciimaps.py
  armi/utils/gridEditor.py
  doc/developer/standards_and_practices.rst
  pyproject.toml
Labels: documentation, cleanup

#2130 Removing unused Parameters
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/physics/neutronics/parameters.py
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
  armi/reactor/reactorParameters.py
  armi/utils/reportPlotting.py
  doc/tutorials/making_your_first_app.rst
Labels: cleanup

#1998 Fixing a couple of plots to use initial block height
  armi/bookkeeping/report/reportingUtils.py
  armi/reactor/converters/uniformMesh.py
  armi/utils/plotting.py
  armi/utils/reportPlotting.py
  armi/utils/tests/test_plotting.py
  armi/utils/tests/test_reportPlotting.py
  doc/gallery-src/framework/run_programmaticReactorDefinition.py
Labels: bug

#2119 Adding basic documentation for axial expansion
  doc/.static/axial_expansion_components.png
  doc/.static/axial_expansion_process.png
  doc/.static/axial_expansion_simple.png
  doc/user/radial_and_axial_expansion.rst
Labels: documentation

#2129 OperatorMPI doesn't need to bcast quits if there no other workers
  armi/operators/operatorMPI.py
Labels: feature request
