Repository terrapower/armi, pull requests merged in 2025-06, with the labels that each got.

#2145 Make axial linking aware of block grids for axial expansion
  armi/reactor/assemblies.py
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/converters/axialExpansionChanger/assemblyAxialLinkage.py
  armi/reactor/converters/axialExpansionChanger/axialExpansionChanger.py
  armi/reactor/converters/axialExpansionChanger/expansionData.py
  armi/reactor/converters/tests/test_assemblyAxialLinkage.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/tests/detailedAxialExpansion/refSmallCoreGrid.yaml
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
  doc/user/radial_and_axial_expansion.rst
Labels: feature request

#2155 Cleaning up strange counter line
  armi/pluginManager.py
Labels: cleanup

#2160 Fixing bad Return in safeCopy
  armi/utils/__init__.py
  armi/utils/plotting.py
Labels: bug

#2168 Removing Deprecation Warning on sortReactor setting
  armi/settings/fwSettings/globalSettings.py
Labels: documentation, cleanup

#2167 Remove unused test code
  armi/reactor/tests/test_assemblies.py
Labels: cleanup, testing
