Repository terrapower/armi, pull requests merged in 2025-01, with the labels that each got.

#2042 Raise error in invalid xsTypeNum condition
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/reactor/tests/test_assemblies.py
  armi/utils/tests/test_reportPlotting.py
Labels: enhancement

#2040 Unpin the max `matplotlib` version, which upgrades numpy
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/databaseInterface.py
  armi/reactor/assemblies.py
  armi/reactor/components/__init__.py
  armi/utils/mathematics.py
  armi/utils/tests/test_iterables.py
  armi/utils/tests/test_tabulate.py
  armi/utils/tests/test_textProcessors.py
  pyproject.toml
Labels: cleanup

#2048 Cleaning up some casual docstrings
  armi/apps.py
  armi/mpiActions.py
  armi/nuclearDataIO/cccc/isotxs.py
  armi/physics/__init__.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/utils/gridEditor.py
Labels: documentation, cleanup

#2052 Removing Database3 from the namespace
  armi/bookkeeping/db/__init__.py
  armi/bookkeeping/db/database3.py
  doc/release/0.5.rst
Labels: architecture, cleanup

#2053 Add python exe file path to Case Information printout
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
Labels: feature request, low priority

#2055 Corrrectly ignoring BP sections in PassiveDBLoadPlugin
  armi/bookkeeping/db/passiveDBLoadPlugin.py
  armi/bookkeeping/db/tests/test_passiveDBLoadPlugin.py
  armi/tests/test_plugins.py
  doc/release/0.5.rst
Labels: bug

#2060 Fix scaling of edge assembly `VOLUME_INTEGRATED` parameters in third core periodic symmetry
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/converters/geometryConverters.py
  armi/reactor/converters/tests/test_geometryConverters.py
  doc/release/0.5.rst
Labels: bug

#2061 Moving our CLA in-house
  CONTRIBUTING.md
  doc/developer/first_time_contributors.rst
Labels: documentation

#2051 Update the check for a jagged array during `_writeParams`
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/tests/test_database3.py
  doc/release/0.5.rst
Labels: bug
