Repository terrapower/armi, pull requests merged in 2025-05, with the labels that each got.

#2121 Supporting growing DBto full core on db load
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/databaseInterface.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/cases/case.py
  armi/operators/tests/test_operatorSnapshots.py
Labels: enhancement

#2132 Removing unused reactivity coeffs params
  armi/physics/neutronics/parameters.py
  armi/reactor/blockParameters.py
  armi/reactor/reactorParameters.py
Labels: cleanup

#2045 Adding a check on the grid/component consistency in the BPs
  armi/reactor/blueprints/blockBlueprint.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
  armi/tests/c5g7/c5g7-blueprints.yaml
Labels: enhancement

#2133 Moving NeutronicsPlugin to its own file
  armi/physics/neutronics/__init__.py
  armi/physics/neutronics/plugin.py
Labels: cleanup

#2118 Adding a FilletedHexagon shape
  armi/reactor/blocks.py
  armi/reactor/components/basicShapes.py
  armi/reactor/components/complexShapes.py
  armi/reactor/components/component.py
  armi/reactor/components/componentParameters.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
Labels: feature request

#2137 Improving description of rateProdNet parameter
  armi/physics/neutronics/parameters.py
Labels: documentation

#2136 Removing unused TH parameters.
  armi/bookkeeping/report/reportingUtils.py
  armi/bookkeeping/report/tests/test_report.py
  armi/physics/thermalHydraulics/parameters.py
  armi/reactor/blockParameters.py
  armi/reactor/reactorParameters.py
  armi/utils/reportPlotting.py
Labels: cleanup

#2139 Removing unnecessary DB load try/except
  armi/bookkeeping/db/database.py
Labels: cleanup

#2135 Retooling single-warnings report as all warnings report
  armi/bookkeeping/mainInterface.py
  armi/runLog.py
  armi/tests/mockRunLogs.py
  armi/tests/test_runLog.py
Labels: feature request

#2140 Cleaning up Block constructor
  armi/reactor/blockParameters.py
  armi/reactor/blocks.py
Labels: cleanup

#2134 Removing unused Parameters
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/parameters.py
  armi/physics/neutronics/settings.py
  armi/reactor/assemblyParameters.py
  armi/reactor/blockParameters.py
  armi/reactor/components/componentParameters.py
  armi/reactor/cores.py
  armi/reactor/reactorParameters.py
  armi/reactor/tests/test_assemblies.py
  armi/tests/anl-afci-177/anl-afci-177-fuelManagement.py
Labels: cleanup

#1995 Improving HexBlock.getFlowArea
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#2142 Quieting warnings from Block.getComponent
  armi/reactor/blocks.py
Labels: feature request

#2146 Some more fstring conversions
  armi/reactor/components/component.py
Labels: cleanup
