Repository terrapower/armi, pull requests merged in 2025-07, with the labels that each got.

#2171 Cleaning up Tests to have Fewer Side Effects
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/reactor/tests/test_excoreStructures.py
Labels: cleanup, testing

#2175 Blocking duplicate flags from being added
  armi/utils/flags.py
  armi/utils/tests/test_flags.py
Labels: enhancement

#2109 Store number densities in numpy arrays instead of dictionary
  armi/bookkeeping/db/compareDB3.py
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/tests/test_databaseInterface.py
  armi/materials/tests/test_air.py
  armi/nucDirectory/nuclideBases.py
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  armi/reactor/components/component.py
  armi/reactor/components/componentParameters.py
  armi/reactor/composites.py
  armi/reactor/cores.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/utils/densityTools.py
  armi/utils/tests/test_densityTools.py
Labels: feature request

#2190 Using iterators instead of getAssemblies where possible
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/reactor/converters/meshConverters.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_geometryConverters.py
  armi/reactor/cores.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_reactors.py
Labels: enhancement
