Repository terrapower/armi, pull requests merged in 2025-03, with the labels that each got.

#2077 Applying expansion for material composition changes
  armi/reactor/components/component.py
  armi/reactor/tests/test_components.py
Labels: feature request

#2076 Adding Requirements and QA to Docs
  .github/workflows/docs.yaml
  .gitignore
  doc/.static/armi_application_structure.png
  doc/.static/css/theme_fixes.css
  doc/.static/needs_templates/test.need
  doc/Makefile
  doc/conf.py
  doc/developer/documenting.rst
  doc/developer/entrypoints.rst
  doc/developer/guide.rst
  doc/developer/making_armi_based_apps.rst
  doc/developer/parallel_coding.rst
  doc/glossary.rst
  doc/index.rst
  doc/make.bat
  doc/qa_docs/index.rst
  doc/qa_docs/sdid.rst
  doc/qa_docs/srsd.rst
  doc/qa_docs/srsd/bookkeeping_reqs.rst
  doc/qa_docs/srsd/cases_reqs.rst
  doc/qa_docs/srsd/cli_reqs.rst
  doc/qa_docs/srsd/framework_reqs.rst
  doc/qa_docs/srsd/materials_reqs.rst
  doc/qa_docs/srsd/nucDirectory_reqs.rst
  doc/qa_docs/srsd/nuclearDataIO_reqs.rst
  doc/qa_docs/srsd/physics_reqs.rst
  doc/qa_docs/srsd/reactors_reqs.rst
  doc/qa_docs/srsd/runLog_reqs.rst
  doc/qa_docs/srsd/settings_reqs.rst
  doc/qa_docs/srsd/utils_reqs.rst
  doc/qa_docs/str.rst
  doc/release/0.5.rst
  doc/user/inputs.rst
  doc/user/manual_data_access.rst
  doc/user/outputs.rst
  doc/user/spatial_block_parameters.rst
  doc/user/user_install.rst
  pyproject.toml
Labels: documentation

#2091 Trying to clean up pytest results table
  .github/workflows/docs.yaml
  README.rst
  armi/nucDirectory/tests/test_elements.py
  armi/nucDirectory/tests/test_nucDirectory.py
  armi/nucDirectory/tests/test_nuclideBases.py
  armi/nuclearDataIO/tests/test_xsLibraries.py
  armi/nuclearDataIO/tests/test_xsNuclides.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/physics/neutronics/tests/test_crossSectionSettings.py
  armi/physics/neutronics/tests/test_energyGroups.py
  armi/reactor/blueprints/tests/test_componentBlueprint.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_blockConverter.py
  armi/reactor/converters/tests/test_meshConverters.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_parameters.py
  armi/settings/tests/test_settingsIO.py
  armi/utils/tests/test_properties.py
  armi/utils/tests/test_tabulate.py
  doc/.static/cleanup_test_results.py
  doc/qa_docs/srsd/nucDirectory_reqs.rst
  doc/qa_docs/srsd/reactors_reqs.rst
  doc/qa_docs/str.rst
Labels: documentation

#2092 Allowing ARMI to use tmp dir on Mac/Linux
  armi/context.py
  doc/release/0.5.rst
  pyproject.toml
Labels: ci

#2095 Edits to STR test report
  .github/workflows/docs.yaml
  doc/.static/css/theme_fixes.css
  doc/.static/needs_templates/test.need
  doc/conf.py
  doc/getTestResults.py
  doc/qa_docs/str.rst
Labels: documentation

#2098 Removing the HTML reports feature
  armi/bookkeeping/__init__.py
  armi/bookkeeping/report/__init__.py
  armi/bookkeeping/report/data.py
  armi/bookkeeping/report/html.py
  armi/bookkeeping/report/newReportUtils.py
  armi/bookkeeping/report/newReports.py
  armi/bookkeeping/report/report.js
  armi/bookkeeping/report/reportInterface.py
  armi/bookkeeping/report/styles.css
  armi/bookkeeping/report/tests/test_newReport.py
  armi/bookkeeping/report/tests/test_report.py
  armi/cases/case.py
  armi/cases/tests/test_cases.py
  armi/cli/checkInputs.py
  armi/cli/reportsEntryPoint.py
  armi/cli/tests/test_runEntryPoint.py
  armi/physics/neutronics/reports.py
  doc/developer/reports.rst
  pyproject.toml
Labels: cleanup

#2090 Adding an SCR section to the docs
  .github/pull_request_template.md
  .github/workflows/docs.yaml
  doc/.static/automateScr.py
  doc/.static/css/theme_fixes.css
  doc/conf.py
  doc/developer/documenting.rst
  doc/developer/first_time_contributors.rst
  doc/developer/parallel_coding.rst
  doc/developer/profiling.rst
  doc/developer/tooling.rst
  doc/index.rst
  doc/qa_docs/index.rst
  doc/qa_docs/scr/0.1.rst
  doc/qa_docs/scr/0.2.rst
  doc/qa_docs/scr/0.3.rst
  doc/qa_docs/scr/0.4.rst
  doc/qa_docs/scr/0.5.rst
  doc/qa_docs/scr/0.6.rst
  doc/qa_docs/scr/index.rst
  doc/release/index.rst
  doc/user/inputs.rst
  doc/user/user_install.rst
  pyproject.toml
Labels: documentation

#2096 Fixing spelling errors
  CONTRIBUTING.md
  README.rst
  armi/__init__.py
  armi/cases/case.py
  armi/cases/suiteBuilder.py
  armi/cli/entryPoint.py
  armi/interfaces.py
  armi/materials/material.py
  armi/materials/water.py
  armi/mpiActions.py
  armi/nucDirectory/nuclideBases.py
  armi/nuclearDataIO/xsCollections.py
  armi/operators/operator.py
  armi/physics/executers.py
  armi/plugins.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/composites.py
  armi/reactor/reactorParameters.py
  armi/reactor/spentFuelPool.py
  armi/reactor/systemLayoutInput.py
  armi/reactor/zones.py
  armi/settings/setting.py
  armi/settings/settingsIO.py
  armi/tests/__init__.py
  armi/tests/test_mpiActions.py
  armi/tests/test_plugins.py
  armi/utils/__init__.py
  armi/utils/asciimaps.py
  armi/utils/customExceptions.py
  armi/utils/flags.py
  armi/utils/gridEditor.py
  armi/utils/plotting.py
  armi/utils/properties.py
  armi/utils/tabulate.py
  armi/utils/textProcessors.py
  armi/utils/triangle.py
  doc/conf.py
  doc/qa_docs/scr/0.1.rst
  doc/qa_docs/sdid.rst
  doc/qa_docs/srsd/physics_reqs.rst
  doc/qa_docs/srsd/reactors_reqs.rst
  doc/user/accessingEntryPoints.rst
  doc/user/inputs.rst
  doc/user/physics_coupling.rst
  doc/user/spatial_block_parameters.rst
Labels: cleanup, low priority

#2101 Fixing issue with SCR on main branch
  .github/workflows/docs.yaml
  doc/.static/automateScr.py
  doc/qa_docs/scr/0.6.rst
Labels: documentation

#2093 Speed up axial expansion unit tests
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/tests/detailedAxialExpansion/refSmallCoreGrid.yaml
Labels: testing

#2104 Clean out references to cinder
  armi/physics/neutronics/const.py
  armi/physics/neutronics/energyGroups.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/physics/neutronics/settings.py
Labels: cleanup
