Repository terrapower/armi, pull requests merged in 2025-09, with the labels that each got.

#2198 Updating Axial Expansion Changer for improved mass redistribution
  armi/bookkeeping/db/database.py
  armi/reactor/blocks.py
  armi/reactor/components/componentParameters.py
  armi/reactor/converters/axialExpansionChanger/assemblyAxialLinkage.py
  armi/reactor/converters/axialExpansionChanger/axialExpansionChanger.py
  armi/reactor/converters/axialExpansionChanger/expansionData.py
  armi/reactor/converters/tests/test_assemblyAxialLinkage.py
  armi/reactor/converters/tests/test_axialExpansionChanger.py
  armi/reactor/converters/tests/test_axialExpansionChanger_MultiPin.py
  armi/testing/singleMixedAssembly.py
  armi/tests/detailedAxialExpansion/refSmallCoreGrid.yaml
  armi/tests/detailedAxialExpansion/refSmallReactorBase.yaml
  armi/utils/densityTools.py
  doc/.static/mass_redistribution_illustration.png
  doc/user/radial_and_axial_expansion.rst
Labels: feature request

#2260 Fixing `compareLines` so that it doesn't trip on zeros
  armi/tests/__init__.py
  armi/tests/test_tests.py
Labels: bug

#2255 Add `b10NumFrac` attribute to B4C class to allow for flexible `setDefaultMassFracs`
  armi/materials/b4c.py
  armi/materials/tests/test_b4c.py
Labels: feature request

#2264 Update the description of the `mcnpLibraryVersion` case setting
  armi/physics/neutronics/settings.py
Labels: documentation

#2219 Refactoring Shuffle Logic Inputs to YAML
  armi/physics/fuelCycle/__init__.py
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/settings.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/cores.py
  armi/settings/settingsValidation.py
  armi/tests/armiRun-SHUFFLES.yaml
  doc/user/inputs.rst
Labels: feature request

#2268 Fixing Uranium enrichment calculations
  armi/reactor/blocks.py
  armi/reactor/composites.py
  armi/reactor/tests/test_blocks.py
Labels: bug

#2269 Track assemblies if discharged to SFP
  armi/physics/fuelCycle/fuelHandlerInterface.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/reactor/cores.py
  armi/settings/fwSettings/globalSettings.py
  armi/tests/armiRun-SHUFFLES.yaml
  doc/user/inputs.rst
Labels: feature request

#2282 Fixing incorrect variable name in Pitch class
  armi/reactor/blueprints/gridBlueprint.py
  armi/reactor/blueprints/tests/test_gridBlueprints.py
Labels: bug

#2278 Adding support for moving assemblies from SFP to Core in YAML shuffle input
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  doc/user/inputs.rst
Labels: feature request

#2263 Adding tests to improve code coverage
  .github/workflows/coverage.yaml
  armi/bookkeeping/db/tests/test_database3.py
  armi/mpiActions.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_composites.py
  armi/tests/test_mpiActions.py
  armi/utils/plotting.py
  armi/utils/tests/test_plotting.py
  armi/utils/tests/test_triangle.py
Labels: testing

#2285 Improving the error messages for invalid settings data
  armi/settings/setting.py
  armi/settings/tests/test_settings.py
Labels: enhancement

#2297 Reducing log spam when creating a lot of spatial grids
  armi/reactor/blueprints/gridBlueprint.py
Labels: cleanup

#2292 Support mixed Blocks for smear density calculation
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#2286 Improving Docs for 0.6.0 Release
  armi/bookkeeping/tests/test_snapshot.py
  armi/nucDirectory/tests/test_elements.py
  armi/nuclearDataIO/tests/test_xsCollections.py
  armi/nuclearDataIO/tests/test_xsNuclides.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  armi/reactor/blueprints/tests/test_blockBlueprints.py
  armi/reactor/blueprints/tests/test_componentBlueprint.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  armi/reactor/converters/tests/test_axialExpansionChanger_MultiPin.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
  armi/settings/tests/test_inspectors.py
  armi/utils/tests/test_tabulate.py
  doc/.static/automateScr.py
  doc/qa_docs/scr/0.6.rst
  doc/qa_docs/str.rst
Labels: documentation

#2302 Handle pin indices for fuel + non fuel on the same grid
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#2305 Raising error if no `driverBlock` is found by latticePhysicsWriter
  armi/physics/neutronics/latticePhysics/latticePhysicsWriter.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeWriter.py
Labels: feature request

#2307 Clearing out Component.p.pinIndices prior to assignment
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: enhancement

#2311 Starting the ARMI 0.6.1 release cycle
  doc/developer/tooling.rst
  doc/qa_docs/scr/0.6.rst
  doc/qa_docs/scr/latest_scr.rst
  pyproject.toml
Labels: documentation
