Repository terrapower/armi, pull requests merged in 2025-02, with the labels that each got.

#2072 Generating ARMI docs also in PDF format
  .github/workflows/docs.yaml
  doc/.static/css/theme_fixes.css
  doc/.static/dochelpers.py
  doc/conf.py
  doc/release/0.5.rst
  doc/user/inputs.rst
  pyproject.toml
Labels: documentation

#2071 Fix application of custom isotopics to work with Fluid classes
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/tests/test_customIsotopics.py
  armi/reactor/blueprints/tests/test_reactorBlueprints.py
  doc/release/0.5.rst
Labels: bug

#2046 Making material modifications more robust against type errors
  armi/reactor/blueprints/componentBlueprint.py
  armi/reactor/blueprints/tests/test_materialModifications.py
Labels: enhancement

#2049 Fix out of date assumption on AZS IDs for "natural nuclides"
  armi/nucDirectory/nuclideBases.py
  armi/nucDirectory/tests/test_nuclideBases.py
Labels: bug

#2050 Update doc build to py313
  .github/workflows/docs.yaml
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/reactor/__init__.py
  armi/runLog.py
  doc/conf.py
  doc/gallery-src/framework/run_chartOfNuclides.py
  doc/gallery-src/framework/run_computeReactionRates.py
  doc/gallery-src/framework/run_fuelManagement.py
  doc/release/0.5.rst
  pyproject.toml
Labels: documentation, ci

#2075 Ignoring Fluid density warning for Component Fluids
  armi/materials/material.py
  armi/materials/tests/test_fluids.py
  armi/materials/tests/test_materials.py
  doc/release/0.5.rst
Labels: feature request

#2074 Revamping Requirements
  armi/apps.py
  armi/bookkeeping/db/database.py
  armi/bookkeeping/db/layout.py
  armi/bookkeeping/db/tests/test_database3.py
  armi/cases/tests/test_cases.py
  armi/materials/material.py
  armi/materials/tests/test_materials.py
  armi/materials/void.py
  armi/physics/fuelCycle/fuelHandlers.py
  armi/physics/fuelCycle/tests/test_fuelHandlers.py
  armi/physics/neutronics/fissionProductModel/tests/test_fissionProductModel.py
  armi/physics/neutronics/globalFlux/globalFluxInterface.py
  armi/physics/neutronics/globalFlux/tests/test_globalFluxInterface.py
  armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py
  armi/physics/neutronics/latticePhysics/tests/test_latticeInterface.py
  armi/physics/neutronics/settings.py
  armi/plugins.py
  armi/reactor/assemblies.py
  armi/reactor/blocks.py
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/cores.py
  armi/reactor/tests/test_assemblies.py
  armi/reactor/tests/test_blocks.py
  armi/reactor/tests/test_components.py
  armi/reactor/tests/test_composites.py
  armi/reactor/tests/test_parameters.py
  armi/reactor/tests/test_reactors.py
  armi/reactor/tests/test_zones.py
  armi/reactor/zones.py
  armi/tests/test_plugins.py
  armi/utils/densityTools.py
  armi/utils/hexagon.py
  armi/utils/tests/test_densityTools.py
  armi/utils/tests/test_hexagon.py
  doc/release/0.5.rst
Labels: documentation

#2079 Removing an unhelpful comment
  armi/bookkeeping/report/reportingUtils.py
Labels: documentation, cleanup

#2078 Removing commit msg checkbox from PR template
  .github/pull_request_template.md
Labels: cleanup

#2081 Remove silent overwrite of `shutil.copy`
  armi/utils/__init__.py
  doc/release/0.5.rst
Labels: cleanup

#2082 Making sure SFPs have spatial grids
  armi/reactor/blueprints/reactorBlueprint.py
  armi/reactor/reactors.py
  armi/reactor/spentFuelPool.py
  armi/reactor/tests/test_blocks.py
  armi/tests/smallestTestReactor/refSmallestReactor.yaml
  doc/release/0.5.rst
Labels: bug

#2069 Expand allowable XS types to include lower case letters
  armi/physics/neutronics/crossSectionGroupManager.py
  armi/physics/neutronics/tests/test_crossSectionManager.py
  doc/user/inputs.rst
Labels: feature request

#1882 Implementing more detailed `__lt__` for components.
  armi/reactor/blocks.py
  armi/reactor/components/__init__.py
  armi/reactor/components/component.py
  armi/reactor/components/volumetricShapes.py
  armi/reactor/tests/test_components.py
  doc/release/0.5.rst
Labels: feature request

#2067 Correctly calculate wetted perimeter for depletable components
  armi/reactor/blocks.py
  armi/reactor/tests/test_blocks.py
Labels: bug

#2083 Improving HexBlock.rotate() docstring
  armi/reactor/blocks.py
Labels: documentation

#2068 Accounting for parent symmetry in component flux calculation
  armi/reactor/components/component.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.5.rst
Labels: bug

#2084 Solving test warnings
  armi/bookkeeping/db/tests/test_comparedb3.py
  armi/reactor/converters/tests/test_uniformMesh.py
  armi/reactor/converters/uniformMesh.py
  armi/utils/tests/test_utils.py
  doc/.static/css/theme_fixes.css
Labels: cleanup, testing

#2086 Account for symmetry factor in `getMgFlux`
  armi/reactor/components/component.py
  armi/reactor/composites.py
  armi/reactor/tests/test_blocks.py
  doc/release/0.5.rst
Labels: bug
